"""Canada filing catalog for a remittance fintech (FinTRAC-registered MSB)."""
from __future__ import annotations

from compliance_agent.fintech import FintechFiling


def _build() -> list[FintechFiling]:
    return [
        # === Regulatory ===
        FintechFiling(
            s_no=0,
            category="Regulatory",
            area="FinTRAC MSB",
            form_name="FinTRAC MSB registration + biennial renewal",
            authority="FinTRAC",
            frequency="Bi-annual (every 2 years)",
            due_date_rule="Initial registration before commencement; renewal in the month of the second anniversary of the previous registration.",
            payment_due="No federal registration fee; failure-to-register administrative monetary penalties up to CAD 500,000 (corporate).",
            applicability="Mandatory",
            applicability_note="Any entity operating as a Money Services Business in Canada (foreign exchange, money transmission, virtual currency).",
        ),
        FintechFiling(
            s_no=0,
            category="Regulatory",
            area="Quebec MSB",
            form_name="AMF Money-Services Business licence (Quebec)",
            authority="Autorité des marchés financiers (Quebec)",
            frequency="Annual",
            due_date_rule="Initial licence before operating in Quebec; annual fees on anniversary.",
            payment_due="Application + annual fees per AMF schedule (CAD ~3,000–10,000 depending on services and locations).",
            applicability="Conditional",
            applicability_note="Required to operate MSB activities in or directed at Quebec residents.",
        ),
        FintechFiling(
            s_no=0,
            category="Regulatory",
            area="Provincial MSB (BC, etc.)",
            form_name="Provincial MSB / consumer protection registrations",
            authority="Provincial regulators (e.g. BC Consumer Protection BC, Ontario consumer affairs)",
            frequency="Annual / Event-based",
            due_date_rule="Per provincial schedule; some provinces have specific money-services or consumer regulations.",
            applicability="Conditional",
        ),

        # === AML / CFT ===
        FintechFiling(
            s_no=0,
            category="AML / CFT",
            area="Suspicious transactions",
            form_name="FinTRAC Suspicious Transaction Report (STR)",
            authority="FinTRAC",
            frequency="Event-based",
            due_date_rule="As soon as practicable after detecting facts that constitute reasonable grounds to suspect.",
            applicability="Mandatory",
        ),
        FintechFiling(
            s_no=0,
            category="AML / CFT",
            area="Large cash transactions",
            form_name="Large Cash Transaction Report (LCTR)",
            authority="FinTRAC",
            frequency="Event-based",
            due_date_rule="Within 15 days of receipt of CAD 10,000+ in cash (single or aggregated within 24h from same person).",
            applicability="Conditional",
        ),
        FintechFiling(
            s_no=0,
            category="AML / CFT",
            area="Electronic funds transfers",
            form_name="Electronic Funds Transfer Report (EFTR)",
            authority="FinTRAC",
            frequency="Event-based",
            due_date_rule="Within 5 working days of any incoming/outgoing international EFT ≥ CAD 10,000 (single or aggregated in 24h).",
            applicability="Mandatory",
            applicability_note="Directly applicable to remittance flows — core reporting obligation.",
        ),
        FintechFiling(
            s_no=0,
            category="AML / CFT",
            area="Virtual currency transfers",
            form_name="Large Virtual Currency Transaction Report (LVCTR)",
            authority="FinTRAC",
            frequency="Event-based",
            due_date_rule="Within 5 working days of any virtual-currency receipt ≥ CAD 10,000 (single or aggregated).",
            applicability="Conditional",
            applicability_note="Applies if the entity handles virtual currency transfers.",
        ),
        FintechFiling(
            s_no=0,
            category="AML / CFT",
            area="Compliance programme",
            form_name="FinTRAC Compliance Effectiveness Review",
            authority="FinTRAC (internal/independent)",
            frequency="Every 2 years",
            due_date_rule="At minimum once every 2 years; review program, training, risk assessment, recordkeeping.",
            applicability="Mandatory",
        ),
        FintechFiling(
            s_no=0,
            category="AML / CFT",
            area="Sanctions",
            form_name="OSFI consolidated sanctions list screening + RAMPS-style reports",
            authority="OSFI / Global Affairs Canada",
            frequency="Continuous + Event-based",
            due_date_rule="Continuous screening; freeze and report property of listed persons immediately.",
            applicability="Mandatory",
        ),

        # === Corporate Tax ===
        FintechFiling(
            s_no=0,
            category="Corporate Tax",
            area="Federal income tax",
            form_name="T2 Corporate Income Tax Return + monthly/quarterly instalments",
            authority="Canada Revenue Agency (CRA)",
            frequency="Annual + Periodic instalments",
            due_date_rule="T2 within 6 months of FY end; balance owing 2 months after FY end (3 months for CCPC).",
            payment_due="Federal CIT 15% (general) + provincial (8–16% by province). Late-payment interest at CRA prescribed rate (compounded daily).",
            applicability="Mandatory",
        ),
        FintechFiling(
            s_no=0,
            category="Corporate Tax",
            area="Quebec CIT",
            form_name="Quebec CO-17 corporate income tax return",
            authority="Revenu Québec",
            frequency="Annual",
            due_date_rule="Within 6 months of FY end (mirrors federal T2).",
            payment_due="Quebec provincial corporate tax 11.5% on top of federal 15%. Late-filing 5% + 1%/month (max 12 months).",
            applicability="Conditional",
            applicability_note="Applies if the corporation has a permanent establishment in Quebec.",
        ),

        # === GST/HST ===
        FintechFiling(
            s_no=0,
            category="GST/HST",
            area="Federal GST/HST",
            form_name="GST/HST Return (GST34)",
            authority="Canada Revenue Agency",
            frequency="Monthly / Quarterly / Annual",
            due_date_rule="Monthly/Quarterly — 1 month after period end; Annual — 3 months after FY end (or 6 months if individual/sole proprietor).",
            payment_due="GST 5% (HST varies 13–15% in HST provinces). 1% penalty on unpaid plus 0.25%/month interest.",
            applicability="Mandatory",
            applicability_note="Most financial services are GST/HST-exempt, but some fee-based services (e.g. service fees) are taxable.",
        ),

        # === PST/QST ===
        FintechFiling(
            s_no=0,
            category="PST/QST",
            area="Quebec sales tax",
            form_name="QST return (Quebec Sales Tax) — VDZ-441",
            authority="Revenu Québec",
            frequency="Monthly / Quarterly",
            due_date_rule="Aligned with GST/HST filing schedule; 1 month after period end.",
            payment_due="QST 9.975% on taxable supplies (compounded on GST in pre-2013 method, separate post-2013). Penalty 7%–15% per Loi sur l'administration fiscale.",
            applicability="Conditional",
            applicability_note="Applies if registered for QST due to Quebec presence or specified-supply thresholds.",
        ),
        FintechFiling(
            s_no=0,
            category="PST/QST",
            area="Other provincial sales tax",
            form_name="PST returns (BC PST / SK PST / MB RST)",
            authority="Provincial tax authority",
            frequency="Monthly",
            due_date_rule="By the last day of the month following the reporting period (provincial schedule).",
            payment_due="BC 7%, SK 6%, MB 7%. Provincial penalties for late filing.",
            applicability="Conditional",
            applicability_note="Applies if the entity is required to collect PST/RST in BC, SK or MB.",
        ),

        # === Payroll ===
        FintechFiling(
            s_no=0,
            category="Payroll",
            area="Source deductions",
            form_name="Payroll source deductions (CPP, EI, federal/provincial income tax) — PD7A",
            authority="Canada Revenue Agency",
            frequency="Monthly / Quarterly / Accelerated",
            due_date_rule="Regular: 15th of next month; Accelerated 1 (threshold $25k): 25th + 10th; Threshold 2 ($100k): 3rd day after pay period.",
            payment_due="Federal + provincial tax withheld + employer share of CPP/EI. Penalty 3–10% of unremitted amount.",
            applicability="Mandatory",
        ),
        FintechFiling(
            s_no=0,
            category="Payroll",
            area="T4 information slip",
            form_name="T4 Statement of Remuneration Paid + T4 Summary",
            authority="Canada Revenue Agency",
            frequency="Annual",
            due_date_rule="By the last day of February following the calendar year.",
            payment_due="No payment; late-filing penalty CAD 100–7,500 by number of slips.",
            applicability="Mandatory",
        ),
        FintechFiling(
            s_no=0,
            category="Payroll",
            area="Quebec payroll",
            form_name="Revenu Québec Source Deductions + RL-1 slip",
            authority="Revenu Québec",
            frequency="Monthly + Annual",
            due_date_rule="Monthly source-deduction remittance per RQ schedule; RL-1 by last day of February.",
            applicability="Conditional",
            applicability_note="Applies for Quebec-resident employees.",
        ),
        FintechFiling(
            s_no=0,
            category="Payroll",
            area="Employer Health Tax",
            form_name="Ontario Employer Health Tax (EHT) Annual Return",
            authority="Ontario Ministry of Finance",
            frequency="Annual + Instalments",
            due_date_rule="Annual return by 15 Mar following calendar year; monthly instalments if remuneration > CAD 600k.",
            payment_due="0.98%–1.95% on Ontario remuneration above CAD 1m exemption.",
            applicability="Conditional",
            applicability_note="Applies if any Ontario employees and total Ontario remuneration above exemption threshold.",
        ),

        # === Pensions ===
        FintechFiling(
            s_no=0,
            category="Pensions",
            area="CPP",
            form_name="Canada Pension Plan contributions (within PD7A remittance)",
            authority="Canada Revenue Agency",
            frequency="Monthly",
            due_date_rule="With payroll source-deduction remittance.",
            payment_due="2024: 5.95% employer + 5.95% employee on pensionable earnings $3,500–$68,500 (CPP base); additional CPP2 on $68,500–$73,200.",
            applicability="Mandatory",
        ),
        FintechFiling(
            s_no=0,
            category="Pensions",
            area="Quebec Pension Plan",
            form_name="QPP contributions (Quebec) — within RQ source deductions",
            authority="Revenu Québec / Retraite Québec",
            frequency="Monthly",
            due_date_rule="With Quebec source-deduction remittance.",
            payment_due="2024: 6.40% employer + 6.40% employee on pensionable earnings; QPP2 from 2024 on additional band.",
            applicability="Conditional",
            applicability_note="Applies for Quebec-resident employees instead of CPP.",
        ),

        # === Social Security ===
        FintechFiling(
            s_no=0,
            category="Social Security",
            area="Employment Insurance",
            form_name="Employment Insurance (EI) contributions",
            authority="Canada Revenue Agency / Service Canada",
            frequency="Monthly",
            due_date_rule="With payroll source-deduction remittance.",
            payment_due="2024: 1.66% employee + 1.4 × employee rate for employer (max insurable earnings $63,200).",
            applicability="Mandatory",
        ),

        # === Workers Compensation ===
        FintechFiling(
            s_no=0,
            category="Workers Compensation",
            area="WSIB Ontario",
            form_name="WSIB premium remittance + annual reconciliation",
            authority="Workplace Safety and Insurance Board (Ontario)",
            frequency="Monthly / Quarterly",
            due_date_rule="By the last day of the month following the reporting period; reconciliation by 31 Mar.",
            payment_due="Premium rate by industry classification (typically 0.2%–6% of insurable earnings up to maximum).",
            applicability="Conditional",
            applicability_note="Applies if any Ontario workers in a covered industry.",
        ),
        FintechFiling(
            s_no=0,
            category="Workers Compensation",
            area="CNESST Quebec",
            form_name="CNESST occupational health & safety contributions",
            authority="CNESST (Quebec)",
            frequency="Monthly / Annual reconciliation",
            due_date_rule="With Quebec source-deduction remittance; annual statement of wages by 15 March.",
            applicability="Conditional",
            applicability_note="Applies for Quebec-resident workers.",
        ),

        # === Information Returns ===
        FintechFiling(
            s_no=0,
            category="Information Returns",
            area="Investment income",
            form_name="T5 Statement of Investment Income",
            authority="Canada Revenue Agency",
            frequency="Annual",
            due_date_rule="By the last day of February following the calendar year.",
            applicability="Conditional",
        ),
        FintechFiling(
            s_no=0,
            category="Information Returns",
            area="Non-resident payments",
            form_name="NR4 — Statement of Amounts Paid or Credited to Non-Residents",
            authority="Canada Revenue Agency",
            frequency="Annual",
            due_date_rule="By 31 March following the calendar year.",
            payment_due="Withholding tax 25% (treaty-reduced where applicable) — paid by the 15th of the following month.",
            applicability="Conditional",
            applicability_note="Triggered by payments to non-residents (interest, royalties, fees).",
        ),
        FintechFiling(
            s_no=0,
            category="Information Returns",
            area="Foreign reporting",
            form_name="T1135 Foreign Income Verification Statement",
            authority="Canada Revenue Agency",
            frequency="Annual",
            due_date_rule="Same as T2 filing deadline.",
            payment_due="No tax; CAD 25/day late filing penalty (min CAD 100, max CAD 2,500) + further gross-negligence penalties.",
            applicability="Conditional",
            applicability_note="Required if cost amount of specified foreign property exceeds CAD 100,000 at any time in the year.",
        ),
        FintechFiling(
            s_no=0,
            category="Information Returns",
            area="CRS / FATCA",
            form_name="FATCA (Part XVIII) + CRS (Part XIX) annual reporting to CRA",
            authority="Canada Revenue Agency",
            frequency="Annual",
            due_date_rule="By 2 May following the calendar year.",
            applicability="Conditional",
            applicability_note="Required if classified as a Reporting Financial Institution under the Income Tax Act.",
        ),

        # === Unclaimed Property ===
        FintechFiling(
            s_no=0,
            category="Unclaimed Property",
            area="Quebec",
            form_name="Quebec Unclaimed Property remittance (Revenu Québec)",
            authority="Revenu Québec",
            frequency="Annual",
            due_date_rule="By 30 April following the calendar year for property unclaimed > 3 years.",
            payment_due="Property remitted in full to Revenu Québec; failure attracts up to 100% penalty.",
            applicability="Conditional",
        ),
        FintechFiling(
            s_no=0,
            category="Unclaimed Property",
            area="Alberta / BC",
            form_name="Provincial unclaimed property remittance (Alberta / BC)",
            authority="Provincial unclaimed property programmes",
            frequency="Annual",
            due_date_rule="Per provincial dormancy schedule (typically 3–5 years dormancy before remittance).",
            applicability="Conditional",
        ),

        # === Corporate & Statutory ===
        FintechFiling(
            s_no=0,
            category="Corporate & Statutory",
            area="Federal corporations",
            form_name="Corporations Canada Annual Return (Form 22)",
            authority="Corporations Canada",
            frequency="Annual",
            due_date_rule="Within 60 days of anniversary date of incorporation.",
            payment_due="Online filing CAD 12; paper CAD 40. Default dissolution risk if missed for 2 years.",
            applicability="Conditional",
            applicability_note="Applies to federally incorporated entities (CBCA).",
        ),
        FintechFiling(
            s_no=0,
            category="Corporate & Statutory",
            area="Provincial corporations",
            form_name="Provincial corporate annual return (e.g. Ontario AR, BC AR)",
            authority="Provincial corporate registrar",
            frequency="Annual",
            due_date_rule="Per province — Ontario online via ONe-Key; BC via Corporate Online by anniversary month.",
            applicability="Conditional",
        ),

        # === Data Protection & Privacy ===
        FintechFiling(
            s_no=0,
            category="Data Protection & Privacy",
            area="PIPEDA",
            form_name="PIPEDA — Privacy Officer, breach reporting to OPC, breach record",
            authority="Office of the Privacy Commissioner (OPC)",
            frequency="Continuous + Event-based",
            due_date_rule="Notify OPC and affected individuals as soon as feasible after a real-risk-of-significant-harm breach; retain breach records for 24 months.",
            applicability="Mandatory",
        ),
        FintechFiling(
            s_no=0,
            category="Data Protection & Privacy",
            area="Quebec Law 25",
            form_name="Quebec Law 25 — privacy officer, privacy impact assessments, breach notification",
            authority="Commission d'accès à l'information (CAI)",
            frequency="Continuous + Event-based",
            due_date_rule="Privacy officer designated; PIAs before high-risk projects; breach notification to CAI and affected individuals as soon as possible.",
            applicability="Conditional",
            applicability_note="Applies to private enterprises processing personal information of Quebec residents.",
        ),

        # === Statistics ===
        FintechFiling(
            s_no=0,
            category="Statistics",
            area="Cross-border statistics",
            form_name="Bank of Canada / Statistics Canada — international transactions survey",
            authority="Statistics Canada / Bank of Canada",
            frequency="Quarterly / Annual",
            due_date_rule="Per StatCan / BoC survey schedules (typically 20–45 days after period close).",
            applicability="Conditional",
            applicability_note="Triggered if surveyed by StatCan (BP-21, BP-59 etc.) — common for fintechs with cross-border flows.",
        ),
    ]


FILINGS = _build()
