"""EU (member-state-neutral) filing catalog for a remittance fintech.

Where a duty rests with the home Member State competent authority (NCA),
the entry names the function generically (e.g. 'NCA prudential return').
Substitute BaFin / CSSF / DNB / ACPR / Bank of Lithuania etc. for the
relevant Member State.
"""
from __future__ import annotations

from compliance_agent.fintech import FintechFiling


def _build() -> list[FintechFiling]:
    return [
        # === Licensing & Authorization ===
        FintechFiling(
            s_no=0,
            category="Regulatory",
            area="Payment institution",
            form_name="PSD2 Payment Institution / E-Money Institution authorization & passporting notifications",
            authority="Home Member State NCA (e.g. BaFin, CSSF, ACPR, DNB, Bank of Lithuania)",
            frequency="One-time + Event-based",
            due_date_rule="Authorization before commencement; passporting notification before providing services in another Member State.",
            applicability="Mandatory",
        ),
        FintechFiling(
            s_no=0,
            category="Regulatory",
            area="Safeguarding",
            form_name="Annual safeguarding auditor's report (client funds)",
            authority="Home Member State NCA",
            frequency="Annual",
            due_date_rule="As prescribed by NCA — typically within 4–6 months of FY close.",
            applicability="Mandatory",
        ),
        FintechFiling(
            s_no=0,
            category="Regulatory",
            area="Prudential reporting",
            form_name="EBA REP — own funds and capital requirements return",
            authority="EBA via NCA",
            frequency="Quarterly",
            due_date_rule="Per EBA reporting calendar (typically 6 weeks after quarter close).",
            applicability="Mandatory",
        ),
        FintechFiling(
            s_no=0,
            category="Regulatory",
            area="Operational & security",
            form_name="EBA Guidelines on ICT and security risk management — annual self-assessment",
            authority="Home Member State NCA",
            frequency="Annual",
            due_date_rule="Typically aligned with FY-end reporting cycle.",
            applicability="Mandatory",
        ),

        # === AML / CFT ===
        FintechFiling(
            s_no=0,
            category="AML / CFT",
            area="Suspicious transaction reporting",
            form_name="Suspicious Transaction / Activity Report to national FIU",
            authority="National FIU (e.g. FIU.NL, TRACFIN, FIU-Lux, AUSTRAC for Australia)",
            frequency="Event-based",
            due_date_rule="Without delay on forming suspicion of money laundering / terrorist financing (AMLD).",
            applicability="Mandatory",
        ),
        FintechFiling(
            s_no=0,
            category="AML / CFT",
            area="Funds transfer information",
            form_name="EU Regulation 2015/847 / 2023/1113 (Travel Rule) compliance — full payer/payee data on transfers",
            authority="Competent authority",
            frequency="Continuous",
            due_date_rule="On every cross-border transfer; for crypto-asset transfers per MiCA + Travel Rule from 30 Dec 2024.",
            applicability="Mandatory",
        ),
        FintechFiling(
            s_no=0,
            category="AML / CFT",
            area="MLRO accountability",
            form_name="Annual MLRO report to senior management / Board",
            authority="Internal + on demand to NCA / FIU",
            frequency="Annual",
            due_date_rule="Per internal policy — typically within 90 days of FY close.",
            applicability="Mandatory",
        ),
        FintechFiling(
            s_no=0,
            category="AML / CFT",
            area="Business-wide risk assessment",
            form_name="Documented enterprise-wide ML/TF risk assessment refresh",
            authority="Home Member State NCA",
            frequency="Annual",
            due_date_rule="At least annually and on material change.",
            applicability="Mandatory",
        ),

        # === Consumer / Conduct ===
        FintechFiling(
            s_no=0,
            category="Consumer Protection",
            area="Cross-border payments transparency",
            form_name="Regulation (EU) 2021/1230 — disclosure of currency-conversion charges",
            authority="Home Member State NCA",
            frequency="Continuous",
            due_date_rule="Pre-transaction disclosure on every cross-border card / credit transfer with currency conversion.",
            applicability="Mandatory",
        ),
        FintechFiling(
            s_no=0,
            category="Consumer Protection",
            area="Complaint handling",
            form_name="Annual complaints report to NCA / ADR body",
            authority="Home Member State NCA + ADR body",
            frequency="Annual",
            due_date_rule="Per NCA prescription — typically within 3 months of FY close.",
            applicability="Mandatory",
        ),

        # === Data Protection ===
        FintechFiling(
            s_no=0,
            category="Data Protection & Privacy",
            area="GDPR",
            form_name="GDPR — ROPA (Art. 30), DPIAs, DPO appointment, breach notification within 72h",
            authority="Lead supervisory authority (e.g. Irish DPC, CNIL)",
            frequency="Continuous + Event-based",
            due_date_rule="ROPA continuous; DPIA before high-risk processing; breach notification within 72 hours of awareness.",
            applicability="Mandatory",
        ),

        # === Cybersecurity ===
        FintechFiling(
            s_no=0,
            category="Cybersecurity",
            area="DORA (Digital Operational Resilience Act)",
            form_name="DORA — ICT risk management, third-party register, TLPT, major incident reporting",
            authority="Home Member State NCA + ESAs (EBA / ESMA / EIOPA)",
            frequency="Continuous + Event-based",
            due_date_rule="Effective 17 Jan 2025; major ICT incident initial notification within 4 hours of classification (max 24h from detection).",
            applicability="Mandatory",
            applicability_note="DORA explicitly covers payment institutions and EMIs.",
        ),
        FintechFiling(
            s_no=0,
            category="Cybersecurity",
            area="NIS2",
            form_name="NIS2 — registration with competent authority, early warning 24h, notification 72h, final report 1m",
            authority="National NIS2 competent authority",
            frequency="Event-based",
            due_date_rule="As per Article 23 timelines (24h / 72h / 1 month).",
            applicability="Conditional",
            applicability_note="Applies if classified as essential / important under national NIS2 transposition.",
        ),

        # === Tax (member-state-specific, names generic) ===
        FintechFiling(
            s_no=0,
            category="VAT",
            area="VAT returns",
            form_name="VAT returns (monthly or quarterly, per State)",
            authority="National tax authority",
            frequency="Monthly / Quarterly",
            due_date_rule="Member-state-specific — typically by 10th–25th of following month/quarter.",
            applicability="Mandatory",
        ),
        FintechFiling(
            s_no=0,
            category="VAT",
            area="Recapitulative statement",
            form_name="EC Sales List / Intrastat (where applicable)",
            authority="National tax authority",
            frequency="Monthly / Quarterly",
            due_date_rule="Member-state-specific; Intrastat thresholds apply.",
            applicability="Conditional",
        ),
        FintechFiling(
            s_no=0,
            category="VAT",
            area="DAC7",
            form_name="DAC7 — digital platform operator reporting",
            authority="National tax authority",
            frequency="Annual",
            due_date_rule="By 31 Jan for the previous calendar year.",
            applicability="Conditional",
            applicability_note="Triggered if the platform facilitates reportable activities (mostly relevant for marketplace components).",
        ),
        FintechFiling(
            s_no=0,
            category="Corporate Tax",
            area="Corporate income tax",
            form_name="Annual corporate income tax return + advance payments",
            authority="National tax authority",
            frequency="Annual + Periodic instalments",
            due_date_rule="Member-state-specific; e.g. NL 5 months after FY close, IE within 9 months, DE 31 Jul (extendable).",
            payment_due="Corporate income tax — rates vary by Member State (e.g. IE 12.5%, NL 25.8%, DE ~30%, LU ~25%, FR 25%). Late-payment interest per national tax code.",
            applicability="Mandatory",
        ),

        # === Corporate ===
        FintechFiling(
            s_no=0,
            category="Corporate & Statutory",
            area="Companies registry",
            form_name="Annual accounts + management report filing with national companies registry",
            authority="National companies registry (e.g. KVK, RCS Lux, Handelsregister)",
            frequency="Annual",
            due_date_rule="Member-state-specific — typically 6–8 months after FY close.",
            applicability="Mandatory",
        ),
        FintechFiling(
            s_no=0,
            category="Corporate & Statutory",
            area="Beneficial ownership",
            form_name="UBO register updates",
            authority="National UBO register",
            frequency="Event-based + Annual confirm",
            due_date_rule="Updates within prescribed days of change; annual confirmation as required.",
            applicability="Mandatory",
        ),

        # === Additional EU entries ===
        FintechFiling(
            s_no=0,
            category="EU Reporting",
            area="Cross-border tax arrangements",
            form_name="DAC6 — reporting of reportable cross-border arrangements",
            authority="National tax authority",
            frequency="Event-based",
            due_date_rule="Within 30 days of arrangement being made available / ready for implementation / first step taken.",
            payment_due="No filing fee; penalties up to €870,000 in some Member States (e.g. NL).",
            applicability="Conditional",
            applicability_note="Triggered by hallmarks (A–E) on cross-border arrangements involving an EU jurisdiction.",
        ),
        FintechFiling(
            s_no=0,
            category="EU Reporting",
            area="CRS / DAC2",
            form_name="Common Reporting Standard / DAC2 — automatic exchange of financial account info",
            authority="National tax authority",
            frequency="Annual",
            due_date_rule="By national deadline (typically end Jun for reporting on prior calendar year).",
            applicability="Conditional",
            applicability_note="Reporting Financial Institution status — many e-money / PIs qualify if maintaining custodial / depository / cash-value accounts.",
        ),
        FintechFiling(
            s_no=0,
            category="AML / CFT",
            area="Fraud reporting",
            form_name="EBA Fraud Reporting (RTS on fraud reporting under PSD2)",
            authority="EBA via NCA",
            frequency="Half-Yearly",
            due_date_rule="Within 2 months of half-year close.",
            applicability="Mandatory",
        ),
        FintechFiling(
            s_no=0,
            category="Consumer Protection",
            area="Whistleblower channels",
            form_name="Whistleblower Protection Directive (EU) 2019/1937 — internal reporting channels",
            authority="National implementing authority",
            frequency="Continuous",
            due_date_rule="Internal reporting channels established; acknowledgement within 7 days; feedback within 3 months.",
            applicability="Mandatory",
            applicability_note="Mandatory for entities ≥ 50 employees (with phased thresholds in some MS).",
        ),
        FintechFiling(
            s_no=0,
            category="Forex / Cross-Border",
            area="Balance of Payments",
            form_name="National central bank BoP / external statistics survey",
            authority="National central bank (e.g. ECB via BBk, DNB, BdF)",
            frequency="Monthly / Quarterly",
            due_date_rule="Per NCB schedule — typically within 15–20 business days of period close.",
            applicability="Conditional",
            applicability_note="Triggered above NCB-specific thresholds for cross-border payments.",
        ),
        FintechFiling(
            s_no=0,
            category="Cybersecurity",
            area="Cyber resilience testing",
            form_name="DORA Threat-Led Penetration Testing (TLPT)",
            authority="Lead overseer (ESA / NCA)",
            frequency="Every 3 years",
            due_date_rule="Identified critical entities tested at least every 3 years; first cycle starts post 17 Jan 2025.",
            applicability="Conditional",
            applicability_note="Required for entities identified by competent authorities as TLPT-in-scope based on cyber risk profile.",
        ),
        FintechFiling(
            s_no=0,
            category="EU Reporting",
            area="CbCR",
            form_name="Country-by-Country Reporting (DAC4)",
            authority="National tax authority",
            frequency="Annual",
            due_date_rule="Notification by FY close; CbCR submission within 12 months of FY close.",
            applicability="Conditional",
            applicability_note="MNE groups with consolidated revenue ≥ €750m.",
        ),
        FintechFiling(
            s_no=0,
            category="VAT",
            area="OSS / IOSS",
            form_name="One-Stop-Shop / Import One-Stop-Shop VAT returns",
            authority="National tax authority",
            frequency="Quarterly (OSS) / Monthly (IOSS)",
            due_date_rule="OSS — by end of month following quarter; IOSS — by end of month following month.",
            applicability="Conditional",
            applicability_note="Applies if supplying B2C digital services / low-value imports into EU consumers.",
        ),
        FintechFiling(
            s_no=0,
            category="Data Protection & Privacy",
            area="ePrivacy / Cookies",
            form_name="ePrivacy Directive (Cookie Law) — consent banners + analytics CMP",
            authority="National DPA (e.g. CNIL, Garante)",
            frequency="Continuous",
            due_date_rule="Consent banner before non-essential cookies; refresh on material change.",
            applicability="Mandatory",
        ),
    ]


FILINGS = _build()
