"""India filing catalog for a remittance fintech."""
from __future__ import annotations

from compliance_agent.fintech import FintechFiling


def _build() -> list[FintechFiling]:
    raw = [
        # === Licensing & Authorization ===
        FintechFiling(
            s_no=0,
            category="Regulatory",
            area="Payment systems",
            form_name="PA-PG Authorization (renewal / annual confirmation)",
            authority="RBI (DPSS)",
            frequency="Annual",
            due_date_rule="Annual confirmation in line with PA-PG Authorization conditions; net-worth statement within 30 days of FY close.",
            payment_due="One-time application fee on submission; net-worth maintenance (₹15 cr minimum, ₹25 cr by 3rd FY end) per RBI PA-PG Guidelines.",
            applicability="Mandatory",
            applicability_note="Required for any entity acting as Payment Aggregator / Payment Gateway under RBI's PA-PG Guidelines.",
        ),
        FintechFiling(
            s_no=0,
            category="Regulatory",
            area="Forex services",
            form_name="MTSS / RDA returns and annual licence renewal (Authorized Dealer Category II)",
            authority="RBI (FED)",
            frequency="Annual",
            due_date_rule="AD Cat-II licence renewable annually; principal-officer attestations and net-owned-funds confirmation per RBI Master Direction.",
            payment_due="Net-owned-funds floor of ₹50 lakh for AD Cat-II (₹5 cr for principal MTSS operators); annual renewal processing fee per RBI.",
            applicability="Mandatory",
            applicability_note="Required for inbound (RDA) and outbound (MTSS) personal remittance flows.",
        ),
        FintechFiling(
            s_no=0,
            category="Regulatory",
            area="Cross-border payments",
            form_name="PA-CB Authorization filings",
            authority="RBI (DPSS)",
            frequency="Annual / Event-based",
            due_date_rule="Authorization conditions per RBI's October 2023 PA-CB framework — import/export PA reporting as prescribed.",
            applicability="Conditional",
            applicability_note="Required if the remittance product processes import (PA-CB-I) or export (PA-CB-E) cross-border collections / disbursals.",
        ),

        # === AML / CFT ===
        FintechFiling(
            s_no=0,
            category="AML / CFT",
            area="Cash transaction reporting",
            form_name="Cash Transaction Report (CTR)",
            authority="FIU-IND",
            frequency="Monthly",
            due_date_rule="By the 15th of the following month.",
            applicability="Mandatory",
            applicability_note="All cash transactions ≥ ₹10 lakh or series of integrally connected transactions aggregating ≥ ₹10 lakh in a month.",
        ),
        FintechFiling(
            s_no=0,
            category="AML / CFT",
            area="Suspicious transaction reporting",
            form_name="Suspicious Transaction Report (STR)",
            authority="FIU-IND",
            frequency="Event-based",
            due_date_rule="Within 7 working days of arriving at the conclusion that a transaction is suspicious.",
            applicability="Mandatory",
        ),
        FintechFiling(
            s_no=0,
            category="AML / CFT",
            area="Cross-border wire transfers",
            form_name="Cross-Border Wire Transfer Report (CBWTR)",
            authority="FIU-IND",
            frequency="Monthly",
            due_date_rule="By the 15th of the following month — all cross-border wire transfers ≥ ₹5 lakh equivalent.",
            applicability="Mandatory",
            applicability_note="Directly applicable to remittance — the core flow.",
        ),
        FintechFiling(
            s_no=0,
            category="AML / CFT",
            area="Counterfeit currency reporting",
            form_name="Counterfeit Currency Report (CCR)",
            authority="FIU-IND",
            frequency="Monthly",
            due_date_rule="By the 15th of the following month.",
            applicability="Conditional",
            applicability_note="Applies if cash handling forms part of the operating model (e.g. cash-in agents).",
        ),
        FintechFiling(
            s_no=0,
            category="AML / CFT",
            area="Non-profit transactions",
            form_name="Non-Profit Organization Transaction Report (NTR)",
            authority="FIU-IND",
            frequency="Monthly",
            due_date_rule="By the 15th of the following month — receipts ≥ ₹10 lakh to/from NPOs.",
            applicability="Conditional",
            applicability_note="Triggered only when NPO-linked transactions are processed.",
        ),
        FintechFiling(
            s_no=0,
            category="AML / CFT",
            area="Risk governance",
            form_name="Annual PMLA Compliance Certificate to the Board",
            authority="Internal (Board) / RBI on demand",
            frequency="Annual",
            due_date_rule="Within 60 days of FY close (31 May), Principal Officer / Designated Director certification.",
            applicability="Mandatory",
        ),
        FintechFiling(
            s_no=0,
            category="AML / CFT",
            area="KYC re-periodicity",
            form_name="Re-KYC reviews (high / medium / low risk)",
            authority="RBI (KYC Master Direction)",
            frequency="Recurring (2/8/10 years by risk)",
            due_date_rule="High-risk every 2 years; medium every 8; low every 10 — tracked per customer ledger.",
            applicability="Mandatory",
        ),

        # === Forex / Cross-Border (FEMA) ===
        FintechFiling(
            s_no=0,
            category="Forex / Cross-Border",
            area="MTSS reporting",
            form_name="MTSS quarterly statements (inward personal remittances)",
            authority="RBI (FED)",
            frequency="Quarterly",
            due_date_rule="Within 15 days of quarter close (Jan-15, Apr-15, Jul-15, Oct-15).",
            applicability="Conditional",
            applicability_note="Applies to inward personal remittance flows under MTSS.",
        ),
        FintechFiling(
            s_no=0,
            category="Forex / Cross-Border",
            area="Foreign liabilities & assets",
            form_name="FLA Annual Return",
            authority="RBI (FED)",
            frequency="Annual",
            due_date_rule="By 15 July, for the previous FY ending 31 March.",
            applicability="Conditional",
            applicability_note="Required if the company received FDI or made overseas investment in any year prior or during the FY.",
        ),
        FintechFiling(
            s_no=0,
            category="Forex / Cross-Border",
            area="FDI reporting",
            form_name="Form FC-GPR (allotment of shares to non-residents)",
            authority="RBI via AD Bank (FIRMS portal)",
            frequency="Event-based",
            due_date_rule="Within 30 days of allotment of shares to a non-resident.",
            applicability="Conditional",
            applicability_note="Triggered on each non-resident allotment, including secondary issues to a parent/holding overseas.",
        ),
        FintechFiling(
            s_no=0,
            category="Forex / Cross-Border",
            area="ECB reporting",
            form_name="Form ECB-2 (External Commercial Borrowings)",
            authority="RBI via AD Bank",
            frequency="Monthly",
            due_date_rule="Within 7 working days of the month-end in which the ECB transaction took place.",
            applicability="Conditional",
            applicability_note="Required if the entity has any outstanding ECB.",
        ),
        FintechFiling(
            s_no=0,
            category="Forex / Cross-Border",
            area="Cross-border outward remittance",
            form_name="Form 15CA / 15CB (remittance certification)",
            authority="Income Tax / AD Bank",
            frequency="Event-based",
            due_date_rule="Before each foreign remittance — 15CA always (Part A/B/C/D as per amount/nature), 15CB from a CA where required.",
            applicability="Mandatory",
            applicability_note="Filed by the remitter; remittance fintech facilitates and retains records.",
        ),

        # === Direct Tax ===
        FintechFiling(
            s_no=0,
            category="Corporate Tax",
            area="Advance tax",
            form_name="Advance tax instalments (Challan ITNS 280)",
            authority="Income Tax Department",
            frequency="Quarterly",
            due_date_rule="15 Jun (15%), 15 Sep (45% cumulative), 15 Dec (75%), 15 Mar (100%).",
            payment_due="Advance tax = 15% (Jun) / 45% (Sep) / 75% (Dec) / 100% (Mar) of estimated annual tax. Interest under 234C if instalments shortfall.",
            applicability="Mandatory",
        ),
        FintechFiling(
            s_no=0,
            category="Payroll",
            area="TDS",
            form_name="Monthly TDS deposit (Challan ITNS 281)",
            authority="Income Tax Department",
            frequency="Monthly",
            due_date_rule="By the 7th of the following month (except March, which is due by 30 April).",
            payment_due="TDS amount deducted in the previous month. Interest at 1.5%/month for late deposit; ₹200/day late filing fee for the quarterly return.",
            applicability="Mandatory",
        ),
        FintechFiling(
            s_no=0,
            category="Payroll",
            area="TDS returns",
            form_name="Form 24Q (salary), 26Q (non-salary resident), 27Q (non-resident)",
            authority="Income Tax Department",
            frequency="Quarterly",
            due_date_rule="31 Jul (Q1), 31 Oct (Q2), 31 Jan (Q3), 31 May (Q4) — Q4 deadline applies for all three forms.",
            applicability="Mandatory",
        ),
        FintechFiling(
            s_no=0,
            category="Information Returns",
            area="TDS certificates",
            form_name="Form 16 / Form 16A issuance",
            authority="Income Tax Department",
            frequency="Quarterly / Annual",
            due_date_rule="Form 16 by 15 Jun; Form 16A within 15 days of TDS return due date for each quarter.",
            applicability="Mandatory",
        ),
        FintechFiling(
            s_no=0,
            category="Corporate Tax",
            area="Income tax return",
            form_name="ITR-6 (companies other than those claiming Sec 11 exemption)",
            authority="Income Tax Department",
            frequency="Annual",
            due_date_rule="By 31 Oct for FY ending 31 Mar (for companies requiring audit).",
            payment_due="Self-assessment tax (after credit for advance tax + TDS) paid before filing; late filing fee ₹5,000 under Sec 234F + interest under 234A/B/C.",
            applicability="Mandatory",
        ),
        FintechFiling(
            s_no=0,
            category="Corporate Tax",
            area="Tax audit",
            form_name="Form 3CA-3CD (Tax audit report)",
            authority="Income Tax Department",
            frequency="Annual",
            due_date_rule="By 30 Sep for FY ending 31 Mar.",
            applicability="Conditional",
            applicability_note="Required if turnover > ₹1 crore (₹10 crore where ≥95% of transactions are non-cash).",
        ),
        FintechFiling(
            s_no=0,
            category="Corporate Tax",
            area="Transfer pricing",
            form_name="Form 3CEB (TP audit report)",
            authority="Income Tax Department",
            frequency="Annual",
            due_date_rule="By 31 Oct — only where international or specified domestic related-party transactions exist.",
            applicability="Conditional",
            applicability_note="Applies if the entity transacts with associated enterprises (e.g. overseas parent for capital, services, IP).",
        ),
        FintechFiling(
            s_no=0,
            category="Information Returns",
            area="Statement of financial transactions",
            form_name="Form 61A (SFT)",
            authority="Income Tax Department",
            frequency="Annual",
            due_date_rule="By 31 May for the preceding FY.",
            applicability="Conditional",
            applicability_note="Triggered by reportable transactions (e.g. cash deposits ≥ ₹10 lakh, FX cards ≥ ₹10 lakh aggregated).",
        ),

        # === Indirect Tax (GST) ===
        FintechFiling(
            s_no=0,
            category="GST/HST",
            area="Outward supplies",
            form_name="GSTR-1",
            authority="GSTN / CBIC",
            frequency="Monthly",
            due_date_rule="By the 11th of the following month (monthly filer); QRMP filers file quarterly by 13th of month following quarter.",
            applicability="Mandatory",
        ),
        FintechFiling(
            s_no=0,
            category="GST/HST",
            area="Summary return",
            form_name="GSTR-3B",
            authority="GSTN / CBIC",
            frequency="Monthly",
            due_date_rule="By the 20th of the following month (monthly filer); QRMP filers by 22nd/24th of month following quarter (by State).",
            payment_due="GST liability per outward tax less eligible ITC. Late fee ₹50/day (₹20/day for nil return); interest 18% p.a. on tax shortfall.",
            applicability="Mandatory",
        ),
        FintechFiling(
            s_no=0,
            category="GST/HST",
            area="Annual return",
            form_name="GSTR-9",
            authority="GSTN / CBIC",
            frequency="Annual",
            due_date_rule="By 31 Dec for the preceding FY.",
            applicability="Mandatory",
            applicability_note="Mandatory if aggregate turnover > ₹2 crore.",
        ),
        FintechFiling(
            s_no=0,
            category="GST/HST",
            area="Annual reconciliation",
            form_name="GSTR-9C",
            authority="GSTN / CBIC",
            frequency="Annual",
            due_date_rule="By 31 Dec for the preceding FY — self-certified reconciliation.",
            applicability="Conditional",
            applicability_note="Mandatory if aggregate turnover > ₹5 crore.",
        ),

        # === Corporate (MCA / ROC) ===
        FintechFiling(
            s_no=0,
            category="Corporate & Statutory",
            area="Annual financials",
            form_name="Form AOC-4 (financial statements)",
            authority="MCA / ROC",
            frequency="Annual",
            due_date_rule="Within 30 days of AGM (AGM by 30 Sep, so typically by 30 Oct).",
            payment_due="ROC filing fee per share-capital slab (typically ₹200–₹600); additional fee ₹100/day for late filing (no cap).",
            applicability="Mandatory",
        ),
        FintechFiling(
            s_no=0,
            category="Corporate & Statutory",
            area="Annual return",
            form_name="Form MGT-7 / MGT-7A",
            authority="MCA / ROC",
            frequency="Annual",
            due_date_rule="Within 60 days of AGM (typically by 29 Nov).",
            payment_due="ROC filing fee per share-capital slab (typically ₹200–₹600); additional fee ₹100/day late.",
            applicability="Mandatory",
        ),
        FintechFiling(
            s_no=0,
            category="Corporate & Statutory",
            area="Auditor appointment",
            form_name="Form ADT-1",
            authority="MCA / ROC",
            frequency="Annual / Event-based",
            due_date_rule="Within 15 days of AGM that appointed/re-appointed the auditor.",
            payment_due="Filing fee ₹200–₹600 by share-capital slab; ₹100/day additional fee on delay.",
            applicability="Mandatory",
        ),
        FintechFiling(
            s_no=0,
            category="Corporate & Statutory",
            area="Director KYC",
            form_name="Form DIR-3 KYC / DIR-3 KYC-WEB",
            authority="MCA",
            frequency="Annual",
            due_date_rule="By 30 Sep for every DIN holder.",
            payment_due="No fee if filed on time; ₹5,000 penalty per DIN once deactivated.",
            applicability="Mandatory",
        ),
        FintechFiling(
            s_no=0,
            category="Corporate & Statutory",
            area="Return of deposits",
            form_name="Form DPT-3",
            authority="MCA / ROC",
            frequency="Annual",
            due_date_rule="By 30 Jun for the preceding FY.",
            payment_due="ROC filing fee per slab (typically ₹200–₹600); ₹100/day additional fee on delay.",
            applicability="Mandatory",
        ),
        FintechFiling(
            s_no=0,
            category="Corporate & Statutory",
            area="MSME dues",
            form_name="Form MSME-1",
            authority="MCA / ROC",
            frequency="Half-Yearly",
            due_date_rule="By 31 Oct (H1: Apr-Sep) and 30 Apr (H2: Oct-Mar) — payments outstanding >45 days to MSME vendors.",
            applicability="Conditional",
            applicability_note="Triggered only if any MSME payments are outstanding > 45 days at half-year close.",
        ),
        FintechFiling(
            s_no=0,
            category="Corporate & Statutory",
            area="Beneficial ownership",
            form_name="Form BEN-2 (Significant Beneficial Ownership)",
            authority="MCA / ROC",
            frequency="Event-based",
            due_date_rule="Within 30 days of receipt of BEN-1 declaration from a significant beneficial owner.",
            applicability="Conditional",
        ),
        FintechFiling(
            s_no=0,
            category="Corporate & Statutory",
            area="Board governance",
            form_name="Board meetings (minimum 4 per FY, max gap 120 days)",
            authority="MCA (Companies Act 2013)",
            frequency="Quarterly",
            due_date_rule="At least one board meeting per quarter with a maximum gap of 120 days.",
            applicability="Mandatory",
        ),

        # === Labor / Payroll ===
        FintechFiling(
            s_no=0,
            category="Pensions",
            area="Provident Fund",
            form_name="EPF monthly challan (ECR) + Form 5 / Form 10",
            authority="EPFO",
            frequency="Monthly",
            due_date_rule="By the 15th of the following month.",
            payment_due="Employer + employee contribution per statute (12% of basic for EPF; 3.25% employer + 0.75% employee for ESI). Interest + damages on delayed payment.",
            applicability="Mandatory",
            applicability_note="Mandatory once headcount ≥ 20.",
        ),
        FintechFiling(
            s_no=0,
            category="Social Security",
            area="Employees' State Insurance",
            form_name="ESI monthly challan",
            authority="ESIC",
            frequency="Monthly",
            due_date_rule="By the 15th of the following month.",
            payment_due="Employer + employee contribution per statute (12% of basic for EPF; 3.25% employer + 0.75% employee for ESI). Interest + damages on delayed payment.",
            applicability="Conditional",
            applicability_note="Applies to employees earning ≤ ₹21,000/month in establishments with ≥ 10 employees (varies by state).",
        ),
        FintechFiling(
            s_no=0,
            category="Payroll",
            area="Professional Tax",
            form_name="Monthly / annual PT returns (state-specific)",
            authority="State commercial-tax department",
            frequency="Monthly / Annual",
            due_date_rule="Varies by State — typically by 10th–20th of following month for monthly States; annual return where prescribed.",
            applicability="Conditional",
            applicability_note="Applies in States that levy PT (e.g. Karnataka, Maharashtra, West Bengal, Telangana).",
        ),
        FintechFiling(
            s_no=0,
            category="Social Security",
            area="Labour Welfare Fund",
            form_name="LWF half-yearly/annual contributions",
            authority="State Labour Welfare Boards",
            frequency="Half-Yearly / Annual",
            due_date_rule="State-specific — e.g. Karnataka annual by 15 Jan; Maharashtra half-yearly Jun/Dec.",
            applicability="Conditional",
        ),

        # === Data Protection & Privacy ===
        FintechFiling(
            s_no=0,
            category="Data Protection & Privacy",
            area="DPDP compliance",
            form_name="Digital Personal Data Protection Act 2023 — notice, consent, DPO, breach reporting",
            authority="Data Protection Board (once notified)",
            frequency="Continuous + Event-based",
            due_date_rule="Notices / DPIA / DPO as operational; breach reporting timelines per Rules once notified.",
            applicability="Mandatory",
        ),

        # === Cybersecurity ===
        FintechFiling(
            s_no=0,
            category="Cybersecurity",
            area="Incident reporting",
            form_name="CERT-In cyber-incident reporting (April 2022 Directions)",
            authority="CERT-In",
            frequency="Event-based",
            due_date_rule="Within 6 hours of noticing or being made aware of a reportable cyber incident.",
            applicability="Mandatory",
        ),
        FintechFiling(
            s_no=0,
            category="Cybersecurity",
            area="Logs retention",
            form_name="ICT log retention (CERT-In Directions)",
            authority="CERT-In",
            frequency="Continuous",
            due_date_rule="Rolling 180 days, stored within Indian jurisdiction.",
            applicability="Mandatory",
        ),
        FintechFiling(
            s_no=0,
            category="Cybersecurity",
            area="System audit",
            form_name="RBI System Audit Report (SAR) for PA-PG / PPI",
            authority="RBI (DPSS)",
            frequency="Annual",
            due_date_rule="Within prescribed timeline after FY close; CERT-In empanelled auditor.",
            applicability="Conditional",
            applicability_note="Applies to authorized PA / PPI / PA-CB entities.",
        ),

        # === Consumer Protection ===
        FintechFiling(
            s_no=0,
            category="Consumer Protection",
            area="Grievance redressal",
            form_name="Customer Grievance Redressal Mechanism & RBI Ombudsman compliance",
            authority="RBI (Integrated Ombudsman Scheme 2021)",
            frequency="Continuous + Annual disclosure",
            due_date_rule="Nodal officer publication, root-cause reporting per RBI directions; ombudsman cases handled per scheme timelines.",
            applicability="Mandatory",
        ),
        FintechFiling(
            s_no=0,
            category="Consumer Protection",
            area="Customer charter / pricing disclosure",
            form_name="Display of charges, fair-practice code, customer charter",
            authority="RBI (Customer Service Master Directions)",
            frequency="Continuous",
            due_date_rule="Published and refreshed alongside any pricing/policy change.",
            applicability="Mandatory",
        ),

        # === Additional regulatory / statutory entries ===
        FintechFiling(
            s_no=0,
            category="Regulatory",
            area="System Audit (SAR)",
            form_name="RBI System Audit Report — annual concurrent audit + SAR submission (PA/PG)",
            authority="RBI (DPSS)",
            frequency="Annual",
            due_date_rule="Within 2 months of FY close — auditor must be CERT-In empanelled.",
            payment_due="Audit fee per engagement (typically ₹10–50 lakh based on scope).",
            applicability="Mandatory",
            applicability_note="Required for all authorised PAs and PG operators.",
        ),
        FintechFiling(
            s_no=0,
            category="AML / CFT",
            area="High-value transactions",
            form_name="High-Value Transaction Reports (HVTR)",
            authority="FIU-IND",
            frequency="Monthly",
            due_date_rule="By the 15th of the following month — transactions ≥ ₹50 lakh per month aggregated.",
            applicability="Conditional",
            applicability_note="Triggered by high-value transactions per FIU-IND HVTR template.",
        ),
        FintechFiling(
            s_no=0,
            category="Information Returns",
            area="TCS",
            form_name="Form 27EQ (Quarterly TCS Return)",
            authority="Income Tax Department",
            frequency="Quarterly",
            due_date_rule="By 15th of month following quarter-end (Q4 by 15 May).",
            payment_due="Tax collected at source — 0.1% – 5% by goods/service category. ₹200/day late filing fee + 1.5%/month interest.",
            applicability="Conditional",
            applicability_note="Triggered for sellers/operators required to collect TCS (e.g. on foreign remittances under LRS ≥ ₹7 lakh from 1 Oct 2023).",
        ),
        FintechFiling(
            s_no=0,
            category="Information Returns",
            area="TCS on LRS / foreign remittance",
            form_name="TCS @ 20% on foreign remittance (other than education/medical) under LRS",
            authority="Income Tax Department",
            frequency="Continuous + Monthly deposit",
            due_date_rule="Collected at point of remittance; deposited monthly with Form 27EQ filed quarterly.",
            payment_due="20% TCS above ₹7 lakh aggregate LRS (5% for education funded by loan; 5% for first ₹7 lakh of education/medical).",
            applicability="Mandatory",
            applicability_note="Directly applicable to outward personal remittance products.",
        ),
        FintechFiling(
            s_no=0,
            category="GST/HST",
            area="E-invoicing",
            form_name="GST e-invoicing on IRP (B2B invoices)",
            authority="GSTN / CBIC",
            frequency="Continuous",
            due_date_rule="IRN generated on each B2B invoice; reporting on IRP within 30 days of invoice date (≥ ₹100 cr turnover).",
            payment_due="No filing fee, but penalty up to ₹10,000 per non-compliant invoice (Sec 122 CGST).",
            applicability="Conditional",
            applicability_note="Mandatory if aggregate turnover > ₹5 crore (from 1 Aug 2023).",
        ),
        FintechFiling(
            s_no=0,
            category="GST/HST",
            area="TDS under GST",
            form_name="GSTR-7 (TDS deductor return)",
            authority="GSTN / CBIC",
            frequency="Monthly",
            due_date_rule="By the 10th of the following month.",
            payment_due="GST-TDS @ 2% (1% CGST + 1% SGST or 2% IGST) on payments to suppliers > ₹2.5 lakh. ₹100/day late fee (capped ₹5,000).",
            applicability="Conditional",
            applicability_note="Applies to specified deductors (typically Govt entities, PSUs); not usually applicable to private remittance fintech.",
        ),
        FintechFiling(
            s_no=0,
            category="GST/HST",
            area="ITC reconciliation",
            form_name="GSTR-2B reconciliation + ITC claim",
            authority="GSTN / CBIC",
            frequency="Monthly",
            due_date_rule="GSTR-2B generated on 14th of following month; ITC claimable basis 2B in GSTR-3B by 20th.",
            applicability="Mandatory",
        ),
        FintechFiling(
            s_no=0,
            category="Corporate & Statutory",
            area="Commencement of business",
            form_name="Form INC-20A (declaration of commencement of business)",
            authority="MCA / ROC",
            frequency="One-time",
            due_date_rule="Within 180 days of incorporation.",
            payment_due="Filing fee ₹200–₹600 by share-capital slab. ₹50,000 penalty on company + ₹1,000/day on each officer for default (capped ₹1 lakh).",
            applicability="Mandatory",
        ),
        FintechFiling(
            s_no=0,
            category="Corporate & Statutory",
            area="CSR (if applicable)",
            form_name="Form CSR-2 (CSR annual report)",
            authority="MCA / ROC",
            frequency="Annual",
            due_date_rule="After AOC-4 (typically by 31 Dec).",
            applicability="Conditional",
            applicability_note="Applies if net worth ≥ ₹500 cr, turnover ≥ ₹1,000 cr or net profit ≥ ₹5 cr in immediately preceding FY.",
        ),
        FintechFiling(
            s_no=0,
            category="Corporate & Statutory",
            area="Charge management",
            form_name="Form CHG-1 / CHG-4 (creation / satisfaction of charges)",
            authority="MCA / ROC",
            frequency="Event-based",
            due_date_rule="Within 30 days of creation/satisfaction of any charge on assets; condonation possible up to 120 days with fee.",
            payment_due="Filing fee by share-capital slab; additional fee scales steeply after 30 days.",
            applicability="Conditional",
        ),
        FintechFiling(
            s_no=0,
            category="Payroll",
            area="POSH Act",
            form_name="POSH Annual Report (Section 21, Sexual Harassment of Women at Workplace Act)",
            authority="District Officer (state)",
            frequency="Annual",
            due_date_rule="By 31 Jan for the preceding calendar year (state-specific).",
            applicability="Mandatory",
            applicability_note="Mandatory if ≥ 10 employees; ICC must be constituted.",
        ),
        FintechFiling(
            s_no=0,
            category="Regulatory",
            area="Shops & Establishments",
            form_name="Shops & Establishments registration / renewal (state-specific)",
            authority="State Labour Department",
            frequency="Annual / One-time depending on state",
            due_date_rule="Within 30 days of commencement; annual renewal in some states (e.g. Karnataka, Maharashtra, Delhi).",
            payment_due="State-specific — typically ₹100–₹10,000 by headcount.",
            applicability="Mandatory",
        ),
        FintechFiling(
            s_no=0,
            category="Pensions",
            area="Gratuity",
            form_name="Gratuity Form A / F (Payment of Gratuity Act 1972)",
            authority="Controlling Authority (state Labour Dept)",
            frequency="One-time + Event-based",
            due_date_rule="Form A (notice of opening) within 30 days of becoming applicable; nomination Form F by each employee.",
            applicability="Mandatory",
            applicability_note="Applies to establishments with ≥ 10 employees.",
        ),
        FintechFiling(
            s_no=0,
            category="Forex / Cross-Border",
            area="RDA reporting",
            form_name="Half-yearly RDA statement (inward personal remittances under Rupee Drawing Arrangement)",
            authority="RBI (FED)",
            frequency="Half-Yearly",
            due_date_rule="Within 30 days of half-year close (Apr-30 / Oct-30).",
            applicability="Conditional",
            applicability_note="Applies to AD Cat-II banks / authorised entities under RDA.",
        ),
        FintechFiling(
            s_no=0,
            category="Forex / Cross-Border",
            area="Annual Performance Report",
            form_name="APR Form for Overseas Direct Investment",
            authority="RBI via AD Bank",
            frequency="Annual",
            due_date_rule="By 31 Dec for the year ended 31 March.",
            applicability="Conditional",
            applicability_note="Required if the entity has made overseas direct investment (ODI) in a Joint Venture or Wholly Owned Subsidiary.",
        ),
        FintechFiling(
            s_no=0,
            category="Corporate Tax",
            area="Transfer Pricing — CbCR",
            form_name="Form 3CEAD (Country-by-Country Report) + Form 3CEAC notification",
            authority="Income Tax Department",
            frequency="Annual",
            due_date_rule="3CEAC within 2 months of FY close; 3CEAD within 12 months of FY close.",
            applicability="Conditional",
            applicability_note="Applies to MNE groups with consolidated revenue ≥ ₹6,400 crore (~€750M).",
        ),
        FintechFiling(
            s_no=0,
            category="Cybersecurity",
            area="Customer awareness",
            form_name="RBI Cyber Fraud Reporting (electronic fraud transactions)",
            authority="RBI (DPSS)",
            frequency="Continuous",
            due_date_rule="Reporting of electronic banking fraud per RBI Master Direction on Customer Service / Cyber Security; CFR portal entries within prescribed days.",
            applicability="Mandatory",
        ),
        FintechFiling(
            s_no=0,
            category="Regulatory",
            area="GIFT-IFSCA (if applicable)",
            form_name="IFSCA registration + periodic returns (Banking / Payment Services Regulations 2024)",
            authority="IFSCA (International Financial Services Centres Authority)",
            frequency="Continuous + Annual",
            due_date_rule="Per IFSCA prescribed returns calendar; annual compliance certification within 90 days of FY close.",
            payment_due="Application fee USD 5,000; annual recurring fee USD 7,500 (Payment Service Provider authorisation in IFSC).",
            applicability="Conditional",
            applicability_note="Applies only if operating in GIFT-IFSC.",
        ),
        FintechFiling(
            s_no=0,
            category="Forex / Cross-Border",
            area="IEC",
            form_name="Importer-Exporter Code (IEC) annual update",
            authority="DGFT",
            frequency="Annual",
            due_date_rule="Annual confirmation between April–June each year; deactivation if not updated.",
            payment_due="No update fee; reactivation fee ₹500.",
            applicability="Conditional",
            applicability_note="Required only if engaged in import/export of goods or services in or from India.",
        ),
    ]
    return raw


FILINGS = _build()
