"""India filing catalog for a remittance fintech."""
from __future__ import annotations

from compliance_agent.fintech import FintechFiling


def _build() -> list[FintechFiling]:
    raw = [
        # === Licensing & Authorization ===
        FintechFiling(
            s_no=0,
            category="Licensing & Authorization",
            area="Payment systems",
            form_name="PA-PG Authorization (renewal / annual confirmation)",
            authority="RBI (DPSS)",
            frequency="Annual",
            due_date_rule="Annual confirmation in line with PA-PG Authorization conditions; net-worth statement within 30 days of FY close.",
            applicability="Mandatory",
            applicability_note="Required for any entity acting as Payment Aggregator / Payment Gateway under RBI's PA-PG Guidelines.",
        ),
        FintechFiling(
            s_no=0,
            category="Licensing & Authorization",
            area="Forex services",
            form_name="MTSS / RDA returns and annual licence renewal (Authorized Dealer Category II)",
            authority="RBI (FED)",
            frequency="Annual",
            due_date_rule="AD Cat-II licence renewable annually; principal-officer attestations and net-owned-funds confirmation per RBI Master Direction.",
            applicability="Mandatory",
            applicability_note="Required for inbound (RDA) and outbound (MTSS) personal remittance flows.",
        ),
        FintechFiling(
            s_no=0,
            category="Licensing & Authorization",
            area="Cross-border payments",
            form_name="PA-CB Authorization filings",
            authority="RBI (DPSS)",
            frequency="Annual / Event-based",
            due_date_rule="Authorization conditions per RBI's October 2023 PA-CB framework — import/export PA reporting as prescribed.",
            applicability="Conditional",
            applicability_note="Required if the remittance product processes import (PA-CB-I) or export (PA-CB-E) cross-border collections / disbursals.",
        ),

        # === AML / CFT ===
        FintechFiling(
            s_no=0,
            category="AML / CFT",
            area="Cash transaction reporting",
            form_name="Cash Transaction Report (CTR)",
            authority="FIU-IND",
            frequency="Monthly",
            due_date_rule="By the 15th of the following month.",
            applicability="Mandatory",
            applicability_note="All cash transactions ≥ ₹10 lakh or series of integrally connected transactions aggregating ≥ ₹10 lakh in a month.",
        ),
        FintechFiling(
            s_no=0,
            category="AML / CFT",
            area="Suspicious transaction reporting",
            form_name="Suspicious Transaction Report (STR)",
            authority="FIU-IND",
            frequency="Event-based",
            due_date_rule="Within 7 working days of arriving at the conclusion that a transaction is suspicious.",
            applicability="Mandatory",
        ),
        FintechFiling(
            s_no=0,
            category="AML / CFT",
            area="Cross-border wire transfers",
            form_name="Cross-Border Wire Transfer Report (CBWTR)",
            authority="FIU-IND",
            frequency="Monthly",
            due_date_rule="By the 15th of the following month — all cross-border wire transfers ≥ ₹5 lakh equivalent.",
            applicability="Mandatory",
            applicability_note="Directly applicable to remittance — the core flow.",
        ),
        FintechFiling(
            s_no=0,
            category="AML / CFT",
            area="Counterfeit currency reporting",
            form_name="Counterfeit Currency Report (CCR)",
            authority="FIU-IND",
            frequency="Monthly",
            due_date_rule="By the 15th of the following month.",
            applicability="Conditional",
            applicability_note="Applies if cash handling forms part of the operating model (e.g. cash-in agents).",
        ),
        FintechFiling(
            s_no=0,
            category="AML / CFT",
            area="Non-profit transactions",
            form_name="Non-Profit Organization Transaction Report (NTR)",
            authority="FIU-IND",
            frequency="Monthly",
            due_date_rule="By the 15th of the following month — receipts ≥ ₹10 lakh to/from NPOs.",
            applicability="Conditional",
            applicability_note="Triggered only when NPO-linked transactions are processed.",
        ),
        FintechFiling(
            s_no=0,
            category="AML / CFT",
            area="Risk governance",
            form_name="Annual PMLA Compliance Certificate to the Board",
            authority="Internal (Board) / RBI on demand",
            frequency="Annual",
            due_date_rule="Within 60 days of FY close (31 May), Principal Officer / Designated Director certification.",
            applicability="Mandatory",
        ),
        FintechFiling(
            s_no=0,
            category="AML / CFT",
            area="KYC re-periodicity",
            form_name="Re-KYC reviews (high / medium / low risk)",
            authority="RBI (KYC Master Direction)",
            frequency="Recurring (2/8/10 years by risk)",
            due_date_rule="High-risk every 2 years; medium every 8; low every 10 — tracked per customer ledger.",
            applicability="Mandatory",
        ),

        # === Forex / Cross-Border (FEMA) ===
        FintechFiling(
            s_no=0,
            category="Forex / Cross-Border",
            area="MTSS reporting",
            form_name="MTSS quarterly statements (inward personal remittances)",
            authority="RBI (FED)",
            frequency="Quarterly",
            due_date_rule="Within 15 days of quarter close (Jan-15, Apr-15, Jul-15, Oct-15).",
            applicability="Conditional",
            applicability_note="Applies to inward personal remittance flows under MTSS.",
        ),
        FintechFiling(
            s_no=0,
            category="Forex / Cross-Border",
            area="Foreign liabilities & assets",
            form_name="FLA Annual Return",
            authority="RBI (FED)",
            frequency="Annual",
            due_date_rule="By 15 July, for the previous FY ending 31 March.",
            applicability="Conditional",
            applicability_note="Required if the company received FDI or made overseas investment in any year prior or during the FY.",
        ),
        FintechFiling(
            s_no=0,
            category="Forex / Cross-Border",
            area="FDI reporting",
            form_name="Form FC-GPR (allotment of shares to non-residents)",
            authority="RBI via AD Bank (FIRMS portal)",
            frequency="Event-based",
            due_date_rule="Within 30 days of allotment of shares to a non-resident.",
            applicability="Conditional",
            applicability_note="Triggered on each non-resident allotment, including secondary issues to a parent/holding overseas.",
        ),
        FintechFiling(
            s_no=0,
            category="Forex / Cross-Border",
            area="ECB reporting",
            form_name="Form ECB-2 (External Commercial Borrowings)",
            authority="RBI via AD Bank",
            frequency="Monthly",
            due_date_rule="Within 7 working days of the month-end in which the ECB transaction took place.",
            applicability="Conditional",
            applicability_note="Required if the entity has any outstanding ECB.",
        ),
        FintechFiling(
            s_no=0,
            category="Forex / Cross-Border",
            area="Cross-border outward remittance",
            form_name="Form 15CA / 15CB (remittance certification)",
            authority="Income Tax / AD Bank",
            frequency="Event-based",
            due_date_rule="Before each foreign remittance — 15CA always (Part A/B/C/D as per amount/nature), 15CB from a CA where required.",
            applicability="Mandatory",
            applicability_note="Filed by the remitter; remittance fintech facilitates and retains records.",
        ),

        # === Direct Tax ===
        FintechFiling(
            s_no=0,
            category="Direct Tax",
            area="Advance tax",
            form_name="Advance tax instalments (Challan ITNS 280)",
            authority="Income Tax Department",
            frequency="Quarterly",
            due_date_rule="15 Jun (15%), 15 Sep (45% cumulative), 15 Dec (75%), 15 Mar (100%).",
            payment_due="On the same dates as the filing.",
            applicability="Mandatory",
        ),
        FintechFiling(
            s_no=0,
            category="Direct Tax",
            area="TDS",
            form_name="Monthly TDS deposit (Challan ITNS 281)",
            authority="Income Tax Department",
            frequency="Monthly",
            due_date_rule="By the 7th of the following month (except March, which is due by 30 April).",
            payment_due="On the same date as the challan filing.",
            applicability="Mandatory",
        ),
        FintechFiling(
            s_no=0,
            category="Direct Tax",
            area="TDS returns",
            form_name="Form 24Q (salary), 26Q (non-salary resident), 27Q (non-resident)",
            authority="Income Tax Department",
            frequency="Quarterly",
            due_date_rule="31 Jul (Q1), 31 Oct (Q2), 31 Jan (Q3), 31 May (Q4) — Q4 deadline applies for all three forms.",
            applicability="Mandatory",
        ),
        FintechFiling(
            s_no=0,
            category="Direct Tax",
            area="TDS certificates",
            form_name="Form 16 / Form 16A issuance",
            authority="Income Tax Department",
            frequency="Quarterly / Annual",
            due_date_rule="Form 16 by 15 Jun; Form 16A within 15 days of TDS return due date for each quarter.",
            applicability="Mandatory",
        ),
        FintechFiling(
            s_no=0,
            category="Direct Tax",
            area="Income tax return",
            form_name="ITR-6 (companies other than those claiming Sec 11 exemption)",
            authority="Income Tax Department",
            frequency="Annual",
            due_date_rule="By 31 Oct for FY ending 31 Mar (for companies requiring audit).",
            applicability="Mandatory",
        ),
        FintechFiling(
            s_no=0,
            category="Direct Tax",
            area="Tax audit",
            form_name="Form 3CA-3CD (Tax audit report)",
            authority="Income Tax Department",
            frequency="Annual",
            due_date_rule="By 30 Sep for FY ending 31 Mar.",
            applicability="Conditional",
            applicability_note="Required if turnover > ₹1 crore (₹10 crore where ≥95% of transactions are non-cash).",
        ),
        FintechFiling(
            s_no=0,
            category="Direct Tax",
            area="Transfer pricing",
            form_name="Form 3CEB (TP audit report)",
            authority="Income Tax Department",
            frequency="Annual",
            due_date_rule="By 31 Oct — only where international or specified domestic related-party transactions exist.",
            applicability="Conditional",
            applicability_note="Applies if the entity transacts with associated enterprises (e.g. overseas parent for capital, services, IP).",
        ),
        FintechFiling(
            s_no=0,
            category="Direct Tax",
            area="Statement of financial transactions",
            form_name="Form 61A (SFT)",
            authority="Income Tax Department",
            frequency="Annual",
            due_date_rule="By 31 May for the preceding FY.",
            applicability="Conditional",
            applicability_note="Triggered by reportable transactions (e.g. cash deposits ≥ ₹10 lakh, FX cards ≥ ₹10 lakh aggregated).",
        ),

        # === Indirect Tax (GST) ===
        FintechFiling(
            s_no=0,
            category="Indirect Tax (GST)",
            area="Outward supplies",
            form_name="GSTR-1",
            authority="GSTN / CBIC",
            frequency="Monthly",
            due_date_rule="By the 11th of the following month (monthly filer); QRMP filers file quarterly by 13th of month following quarter.",
            applicability="Mandatory",
        ),
        FintechFiling(
            s_no=0,
            category="Indirect Tax (GST)",
            area="Summary return",
            form_name="GSTR-3B",
            authority="GSTN / CBIC",
            frequency="Monthly",
            due_date_rule="By the 20th of the following month (monthly filer); QRMP filers by 22nd/24th of month following quarter (by State).",
            payment_due="On the same date as the return.",
            applicability="Mandatory",
        ),
        FintechFiling(
            s_no=0,
            category="Indirect Tax (GST)",
            area="Annual return",
            form_name="GSTR-9",
            authority="GSTN / CBIC",
            frequency="Annual",
            due_date_rule="By 31 Dec for the preceding FY.",
            applicability="Mandatory",
            applicability_note="Mandatory if aggregate turnover > ₹2 crore.",
        ),
        FintechFiling(
            s_no=0,
            category="Indirect Tax (GST)",
            area="Annual reconciliation",
            form_name="GSTR-9C",
            authority="GSTN / CBIC",
            frequency="Annual",
            due_date_rule="By 31 Dec for the preceding FY — self-certified reconciliation.",
            applicability="Conditional",
            applicability_note="Mandatory if aggregate turnover > ₹5 crore.",
        ),

        # === Corporate (MCA / ROC) ===
        FintechFiling(
            s_no=0,
            category="Corporate & Statutory",
            area="Annual financials",
            form_name="Form AOC-4 (financial statements)",
            authority="MCA / ROC",
            frequency="Annual",
            due_date_rule="Within 30 days of AGM (AGM by 30 Sep, so typically by 30 Oct).",
            applicability="Mandatory",
        ),
        FintechFiling(
            s_no=0,
            category="Corporate & Statutory",
            area="Annual return",
            form_name="Form MGT-7 / MGT-7A",
            authority="MCA / ROC",
            frequency="Annual",
            due_date_rule="Within 60 days of AGM (typically by 29 Nov).",
            applicability="Mandatory",
        ),
        FintechFiling(
            s_no=0,
            category="Corporate & Statutory",
            area="Auditor appointment",
            form_name="Form ADT-1",
            authority="MCA / ROC",
            frequency="Annual / Event-based",
            due_date_rule="Within 15 days of AGM that appointed/re-appointed the auditor.",
            applicability="Mandatory",
        ),
        FintechFiling(
            s_no=0,
            category="Corporate & Statutory",
            area="Director KYC",
            form_name="Form DIR-3 KYC / DIR-3 KYC-WEB",
            authority="MCA",
            frequency="Annual",
            due_date_rule="By 30 Sep for every DIN holder.",
            applicability="Mandatory",
        ),
        FintechFiling(
            s_no=0,
            category="Corporate & Statutory",
            area="Return of deposits",
            form_name="Form DPT-3",
            authority="MCA / ROC",
            frequency="Annual",
            due_date_rule="By 30 Jun for the preceding FY.",
            applicability="Mandatory",
        ),
        FintechFiling(
            s_no=0,
            category="Corporate & Statutory",
            area="MSME dues",
            form_name="Form MSME-1",
            authority="MCA / ROC",
            frequency="Half-Yearly",
            due_date_rule="By 31 Oct (H1: Apr-Sep) and 30 Apr (H2: Oct-Mar) — payments outstanding >45 days to MSME vendors.",
            applicability="Conditional",
            applicability_note="Triggered only if any MSME payments are outstanding > 45 days at half-year close.",
        ),
        FintechFiling(
            s_no=0,
            category="Corporate & Statutory",
            area="Beneficial ownership",
            form_name="Form BEN-2 (Significant Beneficial Ownership)",
            authority="MCA / ROC",
            frequency="Event-based",
            due_date_rule="Within 30 days of receipt of BEN-1 declaration from a significant beneficial owner.",
            applicability="Conditional",
        ),
        FintechFiling(
            s_no=0,
            category="Corporate & Statutory",
            area="Board governance",
            form_name="Board meetings (minimum 4 per FY, max gap 120 days)",
            authority="MCA (Companies Act 2013)",
            frequency="Quarterly",
            due_date_rule="At least one board meeting per quarter with a maximum gap of 120 days.",
            applicability="Mandatory",
        ),

        # === Labor / Payroll ===
        FintechFiling(
            s_no=0,
            category="Labor & Payroll",
            area="Provident Fund",
            form_name="EPF monthly challan (ECR) + Form 5 / Form 10",
            authority="EPFO",
            frequency="Monthly",
            due_date_rule="By the 15th of the following month.",
            payment_due="On the same date as the challan.",
            applicability="Mandatory",
            applicability_note="Mandatory once headcount ≥ 20.",
        ),
        FintechFiling(
            s_no=0,
            category="Labor & Payroll",
            area="Employees' State Insurance",
            form_name="ESI monthly challan",
            authority="ESIC",
            frequency="Monthly",
            due_date_rule="By the 15th of the following month.",
            payment_due="On the same date as the challan.",
            applicability="Conditional",
            applicability_note="Applies to employees earning ≤ ₹21,000/month in establishments with ≥ 10 employees (varies by state).",
        ),
        FintechFiling(
            s_no=0,
            category="Labor & Payroll",
            area="Professional Tax",
            form_name="Monthly / annual PT returns (state-specific)",
            authority="State commercial-tax department",
            frequency="Monthly / Annual",
            due_date_rule="Varies by State — typically by 10th–20th of following month for monthly States; annual return where prescribed.",
            applicability="Conditional",
            applicability_note="Applies in States that levy PT (e.g. Karnataka, Maharashtra, West Bengal, Telangana).",
        ),
        FintechFiling(
            s_no=0,
            category="Labor & Payroll",
            area="Labour Welfare Fund",
            form_name="LWF half-yearly/annual contributions",
            authority="State Labour Welfare Boards",
            frequency="Half-Yearly / Annual",
            due_date_rule="State-specific — e.g. Karnataka annual by 15 Jan; Maharashtra half-yearly Jun/Dec.",
            applicability="Conditional",
        ),

        # === Data Protection & Privacy ===
        FintechFiling(
            s_no=0,
            category="Data Protection & Privacy",
            area="DPDP compliance",
            form_name="Digital Personal Data Protection Act 2023 — notice, consent, DPO, breach reporting",
            authority="Data Protection Board (once notified)",
            frequency="Continuous + Event-based",
            due_date_rule="Notices / DPIA / DPO as operational; breach reporting timelines per Rules once notified.",
            applicability="Mandatory",
        ),

        # === Cybersecurity ===
        FintechFiling(
            s_no=0,
            category="Cybersecurity",
            area="Incident reporting",
            form_name="CERT-In cyber-incident reporting (April 2022 Directions)",
            authority="CERT-In",
            frequency="Event-based",
            due_date_rule="Within 6 hours of noticing or being made aware of a reportable cyber incident.",
            applicability="Mandatory",
        ),
        FintechFiling(
            s_no=0,
            category="Cybersecurity",
            area="Logs retention",
            form_name="ICT log retention (CERT-In Directions)",
            authority="CERT-In",
            frequency="Continuous",
            due_date_rule="Rolling 180 days, stored within Indian jurisdiction.",
            applicability="Mandatory",
        ),
        FintechFiling(
            s_no=0,
            category="Cybersecurity",
            area="System audit",
            form_name="RBI System Audit Report (SAR) for PA-PG / PPI",
            authority="RBI (DPSS)",
            frequency="Annual",
            due_date_rule="Within prescribed timeline after FY close; CERT-In empanelled auditor.",
            applicability="Conditional",
            applicability_note="Applies to authorized PA / PPI / PA-CB entities.",
        ),

        # === Consumer Protection ===
        FintechFiling(
            s_no=0,
            category="Consumer Protection",
            area="Grievance redressal",
            form_name="Customer Grievance Redressal Mechanism & RBI Ombudsman compliance",
            authority="RBI (Integrated Ombudsman Scheme 2021)",
            frequency="Continuous + Annual disclosure",
            due_date_rule="Nodal officer publication, root-cause reporting per RBI directions; ombudsman cases handled per scheme timelines.",
            applicability="Mandatory",
        ),
        FintechFiling(
            s_no=0,
            category="Consumer Protection",
            area="Customer charter / pricing disclosure",
            form_name="Display of charges, fair-practice code, customer charter",
            authority="RBI (Customer Service Master Directions)",
            frequency="Continuous",
            due_date_rule="Published and refreshed alongside any pricing/policy change.",
            applicability="Mandatory",
        ),
    ]
    return raw


FILINGS = _build()
