"""Singapore filing catalog for a remittance fintech (MAS Payment Services Act licensee)."""
from __future__ import annotations

from compliance_agent.fintech import FintechFiling


def _build() -> list[FintechFiling]:
    return [
        # === Licensing & Authorization ===
        FintechFiling(
            s_no=0,
            category="Licensing & Authorization",
            area="Payment Services Act",
            form_name="MAS PS Act licence (Money-changing / Standard / Major Payment Institution) — ongoing conditions",
            authority="Monetary Authority of Singapore (MAS)",
            frequency="One-time + Continuous",
            due_date_rule="Authorization before commencement; safeguarding and base-capital tested continuously.",
            applicability="Mandatory",
        ),
        FintechFiling(
            s_no=0,
            category="Licensing & Authorization",
            area="Prudential reporting",
            form_name="MAS PS-N02 — periodic returns (transaction volumes, safeguarding)",
            authority="MAS",
            frequency="Half-Yearly / Annual",
            due_date_rule="As prescribed in PS-N02 — typically 21 days after period close for half-year returns.",
            applicability="Mandatory",
        ),
        FintechFiling(
            s_no=0,
            category="Licensing & Authorization",
            area="Audit",
            form_name="Annual auditor's report + safeguarding audit (PS Act)",
            authority="MAS",
            frequency="Annual",
            due_date_rule="Within 5 months of FY close.",
            applicability="Mandatory",
        ),

        # === AML / CFT ===
        FintechFiling(
            s_no=0,
            category="AML / CFT",
            area="Suspicious Transaction Reporting",
            form_name="STR filing to STRO via SONAR",
            authority="Suspicious Transaction Reporting Office (STRO)",
            frequency="Event-based",
            due_date_rule="Promptly upon forming knowledge or suspicion.",
            applicability="Mandatory",
        ),
        FintechFiling(
            s_no=0,
            category="AML / CFT",
            area="MAS AML/CFT Notices",
            form_name="MAS Notice PSN01 / PSN02 — AML/CFT obligations (CDD, screening, recordkeeping)",
            authority="MAS",
            frequency="Continuous",
            due_date_rule="Continuous CDD on onboarding and ongoing monitoring; CTR-equivalent retention for 5 years.",
            applicability="Mandatory",
        ),
        FintechFiling(
            s_no=0,
            category="AML / CFT",
            area="Targeted financial sanctions",
            form_name="MAS / UN sanctions screening + freeze reports",
            authority="MAS",
            frequency="Continuous + Event-based",
            due_date_rule="Continuous screening; immediate freezing and reporting to MAS on positive match.",
            applicability="Mandatory",
        ),

        # === Data Protection ===
        FintechFiling(
            s_no=0,
            category="Data Protection & Privacy",
            area="PDPA",
            form_name="Singapore PDPA — DPO appointment, consent obligations, 3-day breach notification",
            authority="Personal Data Protection Commission (PDPC)",
            frequency="Continuous + Event-based",
            due_date_rule="Notifiable breach to PDPC no later than 3 calendar days after assessment; affected individuals notified if likely significant harm.",
            applicability="Mandatory",
        ),

        # === Cybersecurity ===
        FintechFiling(
            s_no=0,
            category="Cybersecurity",
            area="MAS Cyber Hygiene",
            form_name="MAS Notice PSN06 / TRM Guidelines — Cyber Hygiene baseline + Technology Risk Management",
            authority="MAS",
            frequency="Continuous + Annual review",
            due_date_rule="Baseline controls continuously enforced; TRM self-assessment per MAS expectations.",
            applicability="Mandatory",
        ),
        FintechFiling(
            s_no=0,
            category="Cybersecurity",
            area="Incident reporting",
            form_name="MAS Notice 644 / PSN06 — incident notification (1-hour relevant incidents)",
            authority="MAS",
            frequency="Event-based",
            due_date_rule="Within 1 hour upon discovery of a 'relevant incident'; root-cause analysis within 14 days.",
            applicability="Mandatory",
        ),
        FintechFiling(
            s_no=0,
            category="Cybersecurity",
            area="Outsourcing",
            form_name="MAS Guidelines on Outsourcing — register of outsourcing arrangements + notification of material outsourcing",
            authority="MAS",
            frequency="Continuous + Event-based",
            due_date_rule="Register maintained continuously; pre-engagement notification for material outsourcing.",
            applicability="Mandatory",
        ),

        # === Tax ===
        FintechFiling(
            s_no=0,
            category="Indirect Tax (GST)",
            area="GST",
            form_name="GST Form 5",
            authority="IRAS",
            frequency="Quarterly",
            due_date_rule="By 30 days after end of accounting period (electronic filing).",
            payment_due="GST = output tax (9%) less allowable input tax. Late lodgement fee SGD 200; 5% penalty on tax unpaid.",
            applicability="Mandatory",
        ),
        FintechFiling(
            s_no=0,
            category="Direct Tax",
            area="Corporate Income Tax",
            form_name="Form C / C-S + ECI (Estimated Chargeable Income)",
            authority="IRAS",
            frequency="Annual",
            due_date_rule="ECI within 3 months of FY close; Form C / C-S by 30 Nov.",
            payment_due="Singapore corporate tax @ 17% on chargeable income (partial exemption — first SGD 10,000 @ 4.25%, next SGD 190,000 @ 8.5%). Paid in 12 instalments via GIRO.",
            applicability="Mandatory",
        ),
        FintechFiling(
            s_no=0,
            category="Labor & Payroll",
            area="CPF",
            form_name="CPF monthly contribution + IR8A annual return of employee earnings",
            authority="CPF Board / IRAS",
            frequency="Monthly + Annual",
            due_date_rule="CPF by 14th of following month; IR8A by 1 Mar.",
            payment_due="CPF by 14th of following month.",
            applicability="Mandatory",
        ),

        # === Corporate ===
        FintechFiling(
            s_no=0,
            category="Corporate & Statutory",
            area="ACRA",
            form_name="Annual Return (ACRA) + AGM (where applicable)",
            authority="ACRA",
            frequency="Annual",
            due_date_rule="Annual Return within 7 months of FY close (private company); AGM within 6 months of FY close.",
            payment_due="ACRA filing fee SGD 60 (annual return). Late lodgement penalty from SGD 300 (and risk of strike-off).",
            applicability="Mandatory",
        ),
        FintechFiling(
            s_no=0,
            category="Corporate & Statutory",
            area="Register of Controllers",
            form_name="Register of Registrable Controllers + ACRA notifications",
            authority="ACRA",
            frequency="Event-based",
            due_date_rule="Updates within 2 business days of becoming aware of change; ACRA filings within 2 business days of update.",
            applicability="Mandatory",
        ),

        # === Additional Singapore entries ===
        FintechFiling(
            s_no=0,
            category="Direct Tax",
            area="Withholding Tax",
            form_name="IRAS Form IR37 (Withholding Tax on payments to non-residents)",
            authority="IRAS",
            frequency="Monthly",
            due_date_rule="By 15th of second month following date of payment to non-resident.",
            payment_due="WHT rates — 15% interest, 10% royalties, 17% (CIT) on services / management fees (treaty-reduced where applicable).",
            applicability="Conditional",
            applicability_note="Triggered on payments to non-residents — interest, royalties, technical / management fees.",
        ),
        FintechFiling(
            s_no=0,
            category="Labor & Payroll",
            area="Foreign workforce",
            form_name="MOM Form IR21 (cessation of foreign employee employment)",
            authority="Inland Revenue Authority of Singapore",
            frequency="Event-based",
            due_date_rule="At least 1 month before cessation; employer must withhold all monies due.",
            applicability="Conditional",
            applicability_note="Applies on cessation / overseas posting of foreign workforce.",
        ),
        FintechFiling(
            s_no=0,
            category="Labor & Payroll",
            area="Work Pass / EP / S Pass",
            form_name="MOM Work Pass applications & renewals (EP / S Pass / DP / Tech.Pass)",
            authority="Ministry of Manpower",
            frequency="Event-based + Renewal",
            due_date_rule="Initial applications before start; renewals 1–6 months before expiry per pass type.",
            payment_due="EP renewal SGD 225; S Pass renewal SGD 100 + monthly levy (SGD 330–550 per S Pass holder).",
            applicability="Conditional",
        ),
        FintechFiling(
            s_no=0,
            category="Labor & Payroll",
            area="Skills Future Levy",
            form_name="Skills Development Levy (SDL)",
            authority="SkillsFuture Singapore (via CPF Board)",
            frequency="Monthly",
            due_date_rule="With CPF contribution (by 14th of following month).",
            payment_due="0.25% of monthly wages, minimum SGD 2, capped SGD 11.25 per employee.",
            applicability="Mandatory",
        ),
        FintechFiling(
            s_no=0,
            category="Direct Tax",
            area="Transfer Pricing",
            form_name="IRAS TP Documentation + Form for Reporting of Related-Party Transactions",
            authority="IRAS",
            frequency="Annual",
            due_date_rule="TP documentation contemporaneously with related-party transactions; RPT Form with Form C if related-party transactions > SGD 15m.",
            payment_due="No filing fee; surcharge of 5% on TP adjustments.",
            applicability="Conditional",
            applicability_note="Required if related-party transactions exceed prescribed thresholds.",
        ),
        FintechFiling(
            s_no=0,
            category="Direct Tax",
            area="CRS / FATCA",
            form_name="IRAS CRS / FATCA reporting",
            authority="IRAS",
            frequency="Annual",
            due_date_rule="By 31 May following reporting calendar year.",
            applicability="Conditional",
            applicability_note="Applies if Singapore-based Reporting Financial Institution.",
        ),
        FintechFiling(
            s_no=0,
            category="Consumer Protection",
            area="Fair Dealing",
            form_name="MAS Fair Dealing Guidelines — board-level oversight + outcomes monitoring",
            authority="MAS",
            frequency="Continuous + Annual review",
            due_date_rule="Board reviews fair-dealing outcomes at least annually.",
            applicability="Mandatory",
        ),
        FintechFiling(
            s_no=0,
            category="Cybersecurity",
            area="Outsourcing register",
            form_name="MAS Outsourcing register — material outsourcing inventory",
            authority="MAS",
            frequency="Continuous + Annual review",
            due_date_rule="Register maintained continuously; reviewed at least annually with formal sign-off.",
            applicability="Mandatory",
        ),
    ]


FILINGS = _build()
