"""UK filing catalog for a remittance fintech (FCA Authorised Payment Institution)."""
from __future__ import annotations

from compliance_agent.fintech import FintechFiling


def _build() -> list[FintechFiling]:
    return [
        # === Licensing & Authorization ===
        FintechFiling(
            s_no=0,
            category="Regulatory",
            area="Payment Services",
            form_name="FCA Authorised Payment Institution permission (PSR 2017) + ongoing change-in-control notifications",
            authority="FCA",
            frequency="One-time + Event-based",
            due_date_rule="Authorization before commencement; change-in-control notification before completion of change.",
            payment_due="Application fee ~£5,000 (small PI) to £25,000 (API); annual periodic fee per FCA fee-block A.10 (minimum ~£1,151).",
            applicability="Mandatory",
        ),
        FintechFiling(
            s_no=0,
            category="Regulatory",
            area="Regulatory reporting",
            form_name="FCA Regulatory Returns (FSA056 / REP017 etc.) via GABRIEL/RegData",
            authority="FCA",
            frequency="Monthly / Quarterly / Annual",
            due_date_rule="Per RegData schedule for each return — typically 15–30 business days after period close.",
            applicability="Mandatory",
        ),
        FintechFiling(
            s_no=0,
            category="Regulatory",
            area="Safeguarding",
            form_name="Annual safeguarding audit + monthly safeguarding reconciliation",
            authority="FCA",
            frequency="Annual + Monthly",
            due_date_rule="Annual audit within 4 months of FY close; safeguarding reconciliation as often as accounting records are produced.",
            applicability="Mandatory",
        ),
        FintechFiling(
            s_no=0,
            category="Regulatory",
            area="Senior Managers & Certification Regime",
            form_name="SMCR Form A (approvals), Conduct Rules training, annual certification",
            authority="FCA",
            frequency="Annual + Event-based",
            due_date_rule="Approvals before role start; annual certification at least once every 12 months.",
            applicability="Mandatory",
        ),

        # === AML / CFT ===
        FintechFiling(
            s_no=0,
            category="AML / CFT",
            area="Suspicious Activity Reports",
            form_name="SAR / DAML submissions to NCA via SAR Online",
            authority="National Crime Agency (NCA)",
            frequency="Event-based",
            due_date_rule="As soon as practicable after suspicion forms; DAML (defence) before proceeding with the transaction.",
            applicability="Mandatory",
        ),
        FintechFiling(
            s_no=0,
            category="AML / CFT",
            area="MLR 2017",
            form_name="Annual MLRO report + business-wide risk assessment refresh",
            authority="Internal + FCA on request",
            frequency="Annual",
            due_date_rule="Within 90 days of FY close.",
            applicability="Mandatory",
        ),
        FintechFiling(
            s_no=0,
            category="AML / CFT",
            area="Sanctions",
            form_name="OFSI consolidated sanctions list screening + reports of breaches/frozen funds",
            authority="OFSI (HM Treasury)",
            frequency="Continuous + Event-based + Annual",
            due_date_rule="Screening on every transaction; breach reports as soon as practicable; annual frozen-funds report by deadline OFSI sets each year.",
            applicability="Mandatory",
        ),

        # === Consumer Protection ===
        FintechFiling(
            s_no=0,
            category="Consumer Protection",
            area="Consumer Duty",
            form_name="FCA Consumer Duty — annual board attestation + outcomes monitoring",
            authority="FCA",
            frequency="Annual",
            due_date_rule="Annual board review and attestation within 12 months of last (first by 31 Jul 2024).",
            applicability="Mandatory",
        ),
        FintechFiling(
            s_no=0,
            category="Consumer Protection",
            area="Complaints",
            form_name="DISP complaints return + Financial Ombudsman cooperation",
            authority="FCA / Financial Ombudsman Service",
            frequency="Half-Yearly",
            due_date_rule="30 business days after each reporting period (DISP 1 Annex 1).",
            applicability="Mandatory",
        ),
        FintechFiling(
            s_no=0,
            category="Consumer Protection",
            area="APP fraud reimbursement",
            form_name="PSR Authorised Push Payment Fraud reimbursement — data reporting",
            authority="PSR / Pay.UK",
            frequency="Monthly / Quarterly",
            due_date_rule="Per PSR mandatory reimbursement scheme (effective Oct 2024) — data submissions on the PSR schedule.",
            applicability="Conditional",
            applicability_note="Applies to Faster Payments and CHAPS participants serving consumers in the UK.",
        ),

        # === Data Protection ===
        FintechFiling(
            s_no=0,
            category="Data Protection & Privacy",
            area="UK GDPR / DPA 2018",
            form_name="UK GDPR + DPA 2018 — ICO registration, DPO contact, ROPA, 72h breach reports",
            authority="Information Commissioner's Office (ICO)",
            frequency="Annual + Continuous + Event-based",
            due_date_rule="ICO data-protection fee paid annually on anniversary; breach to ICO within 72 hours of awareness.",
            payment_due="ICO fee — Tier 1 £40 (turnover ≤£632k or ≤10 staff), Tier 2 £60 (≤£36m or ≤250 staff), Tier 3 £2,900 (larger).",
            applicability="Mandatory",
        ),

        # === Cybersecurity ===
        FintechFiling(
            s_no=0,
            category="Cybersecurity",
            area="Operational resilience",
            form_name="FCA / Bank of England Operational Resilience policy — important business services & impact tolerances",
            authority="FCA",
            frequency="Continuous + Annual review",
            due_date_rule="Self-assessment maintained; full operational-resilience compliance by 31 Mar 2025.",
            applicability="Mandatory",
        ),
        FintechFiling(
            s_no=0,
            category="Cybersecurity",
            area="Incident reporting",
            form_name="FCA Principle 11 incident notifications + REP018 operational/security incident reporting",
            authority="FCA",
            frequency="Event-based",
            due_date_rule="As soon as reasonably practicable on becoming aware of a material incident.",
            applicability="Mandatory",
        ),

        # === Tax ===
        FintechFiling(
            s_no=0,
            category="Corporate Tax",
            area="Corporation Tax",
            form_name="CT600 + iXBRL accounts + Corporation Tax payment",
            authority="HMRC",
            frequency="Annual + Quarterly (large)",
            due_date_rule="CT600 within 12 months of FY close; CT payment within 9 months & 1 day (large companies on quarterly instalments).",
            payment_due="UK Corporation Tax = 25% on profits > £250k (19% main rate up to £50k, marginal relief between). Late-payment interest rate per HMRC (currently 8.0%).",
            applicability="Mandatory",
        ),
        FintechFiling(
            s_no=0,
            category="VAT",
            area="VAT",
            form_name="VAT return (Making Tax Digital)",
            authority="HMRC",
            frequency="Quarterly",
            due_date_rule="Filing + payment within 1 month and 7 days after VAT-quarter close.",
            payment_due="VAT = output VAT less input VAT. Default surcharge regime — 2%, 5%, 10%, 15% of unpaid VAT for repeated lateness.",
            applicability="Mandatory",
        ),
        FintechFiling(
            s_no=0,
            category="Payroll",
            area="PAYE",
            form_name="PAYE / NIC RTI submissions (FPS / EPS) + P11D",
            authority="HMRC",
            frequency="Monthly + Annual",
            due_date_rule="FPS on or before each payday; P11D for benefits by 6 Jul; PAYE settlement payments per HMRC schedule.",
            payment_due="By the 22nd of the following month (electronic).",
            applicability="Mandatory",
        ),

        # === Corporate ===
        FintechFiling(
            s_no=0,
            category="Corporate & Statutory",
            area="Companies House",
            form_name="Confirmation Statement (CS01) + Annual Accounts + PSC register updates",
            authority="Companies House",
            frequency="Annual + Event-based",
            due_date_rule="Confirmation Statement within 14 days of review date; accounts within 9 months of FY close; PSC updates within 14 days of internal record and 14 days more to register.",
            payment_due="CS01 fee £34 online (£62 paper). Late accounts penalty £150–£1,500 (private), doubled if late in two consecutive years.",
            applicability="Mandatory",
        ),
        FintechFiling(
            s_no=0,
            category="Corporate & Statutory",
            area="ECCT 2023",
            form_name="Economic Crime and Corporate Transparency Act — identity verification, ACSP registration",
            authority="Companies House",
            frequency="Continuous + Event-based",
            due_date_rule="Per Companies House phased implementation through 2024–2026.",
            applicability="Mandatory",
        ),

        # === Additional UK entries ===
        FintechFiling(
            s_no=0,
            category="Pensions",
            area="Auto-enrolment pensions",
            form_name="Auto-enrolment pension contributions (monthly remittance)",
            authority="The Pensions Regulator / scheme provider",
            frequency="Monthly",
            due_date_rule="Typically by 22nd of the month following deduction (scheme rules apply).",
            payment_due="Employer minimum 3% + employee 5% of qualifying earnings (total 8%). Scheme-specific late-payment notices to TPR.",
            applicability="Mandatory",
            applicability_note="Mandatory once any UK employee aged 22–SPA earning ≥£10,000 is present.",
        ),
        FintechFiling(
            s_no=0,
            category="Pensions",
            area="Pensions re-enrolment",
            form_name="Re-enrolment + Declaration of Compliance to TPR",
            authority="The Pensions Regulator",
            frequency="Every 3 years",
            due_date_rule="Re-enrol eligible jobholders every 3 years from staging date; declaration within 5 months of re-enrolment date.",
            payment_due="No filing fee; £400 fixed penalty + escalating daily penalty (£50–£10,000) on default.",
            applicability="Mandatory",
        ),
        FintechFiling(
            s_no=0,
            category="Payroll",
            area="P11D(b) Class 1A NIC",
            form_name="P11D(b) — Class 1A NIC return on benefits in kind",
            authority="HMRC",
            frequency="Annual",
            due_date_rule="By 6 Jul following tax year-end (5 Apr).",
            payment_due="Class 1A NIC @ 13.8% on taxable benefits; payable by 22 Jul (electronic).",
            applicability="Conditional",
            applicability_note="Required if any P11D-reportable benefits provided to employees.",
        ),
        FintechFiling(
            s_no=0,
            category="Payroll",
            area="Employment-Related Securities",
            form_name="ERS annual return (incl. EMI / CSOP / unapproved schemes)",
            authority="HMRC",
            frequency="Annual",
            due_date_rule="By 6 Jul following tax year-end.",
            payment_due="No payment, but £100 late penalty + further £300 escalations.",
            applicability="Conditional",
            applicability_note="Required if any employee share-incentive scheme exists (incl. growth shares, EMI options).",
        ),
        FintechFiling(
            s_no=0,
            category="Corporate Tax",
            area="Corporation Tax QIP",
            form_name="Corporation Tax — Quarterly Instalment Payments (large/very large companies)",
            authority="HMRC",
            frequency="Quarterly",
            due_date_rule="Large (profits > £1.5m): 4 instalments — 7th month of AP, 10th month of AP, 13th, 16th. Very large (> £20m): brought forward by 4 months.",
            payment_due="25% of expected total CT per instalment. Interest 4–8% on underpaid instalments (HMRC late-interest rate).",
            applicability="Conditional",
            applicability_note="Mandatory once augmented profits cross £1.5m threshold (group-adjusted).",
        ),
        FintechFiling(
            s_no=0,
            category="Accounting Control",
            area="Senior Accounting Officer",
            form_name="SAO certificate (Senior Accounting Officer)",
            authority="HMRC",
            frequency="Annual",
            due_date_rule="With annual accounts (within 9 months of FY close).",
            payment_due="No filing fee; £5,000 personal penalty on SAO for failure to certify or notify; further £5,000 on the company.",
            applicability="Conditional",
            applicability_note="Required if UK turnover > £200m or balance sheet > £2bn (group level).",
        ),
        FintechFiling(
            s_no=0,
            category="Consumer Protection",
            area="Modern Slavery",
            form_name="Modern Slavery Statement (s.54 Modern Slavery Act 2015)",
            authority="Home Office (online register)",
            frequency="Annual",
            due_date_rule="Within 6 months of FY close; published on the company website and Home Office register.",
            applicability="Conditional",
            applicability_note="Required if global turnover ≥ £36m and any UK business presence.",
        ),
        FintechFiling(
            s_no=0,
            category="Payroll",
            area="Gender Pay Gap",
            form_name="Gender Pay Gap Report",
            authority="Government Equalities Office / GOV.UK portal",
            frequency="Annual",
            due_date_rule="By 4 Apr each year (private sector) for snapshot 5 Apr prior.",
            applicability="Conditional",
            applicability_note="Required if ≥ 250 UK employees on snapshot date.",
        ),
        FintechFiling(
            s_no=0,
            category="Data Protection & Privacy",
            area="CRS / FATCA",
            form_name="HMRC FATCA / CRS reporting (Form CRS / FATCA XML schema)",
            authority="HMRC",
            frequency="Annual",
            due_date_rule="By 31 May following calendar year.",
            payment_due="No fee; £300 penalty per return + £60/day for continued failure.",
            applicability="Conditional",
            applicability_note="Required if classified as a Financial Institution under CRS; many e-money/PI firms qualify.",
        ),
        FintechFiling(
            s_no=0,
            category="AML / CFT",
            area="HMRC AML supervision",
            form_name="HMRC AML supervised business — annual fees + register update (if not FCA-supervised)",
            authority="HMRC",
            frequency="Annual",
            due_date_rule="Per HMRC anniversary cycle; nomination fees due on registration.",
            payment_due="Registration fee £300 per premises; renewal fee £300/yr; approval test fee £150 per nominated officer.",
            applicability="Conditional",
            applicability_note="HMRC-supervised only — FCA-authorised PIs are FCA-supervised for AML and skip this.",
        ),
        FintechFiling(
            s_no=0,
            category="Consumer Protection",
            area="FSCS",
            form_name="Financial Services Compensation Scheme tariff data submission",
            authority="FSCS via FCA",
            frequency="Annual",
            due_date_rule="Tariff data window typically Jul–Sep each year via FCA RegData.",
            payment_due="FSCS levy per class — variable; small PIs typically exempt from class-specific levies.",
            applicability="Conditional",
        ),
        FintechFiling(
            s_no=0,
            category="Payroll",
            area="Off-payroll working",
            form_name="IR35 / Off-Payroll Working (ITEPA Ch.10) compliance",
            authority="HMRC",
            frequency="Continuous",
            due_date_rule="Status Determination Statement issued before any engagement begins; client-led status decisions for medium/large businesses.",
            applicability="Conditional",
            applicability_note="Required if engaging contractors via intermediary entities (PSCs) and company is medium/large.",
        ),
        FintechFiling(
            s_no=0,
            category="CIS",
            area="Construction Industry Scheme",
            form_name="CIS300 monthly contractor return + CIS deductions",
            authority="HMRC",
            frequency="Monthly",
            due_date_rule="CIS300 by 19th of the tax month (5th); payment by 22nd (electronic) following tax month.",
            payment_due="20% (verified subcontractor) / 30% (unverified) of payment net of materials. £100+ penalty for late return + interest.",
            applicability="Conditional",
            applicability_note="Triggered only if engaging construction-sector subcontractors (rarely applicable to a remittance fintech; included for completeness).",
        ),
        FintechFiling(
            s_no=0,
            category="Statistics",
            area="Bank of England",
            form_name="Bank of England statistical returns (Form FS / BE / BoP surveys)",
            authority="Bank of England",
            frequency="Quarterly / Annual",
            due_date_rule="Per BoE Statistical Code of Practice — typically 4–6 weeks after period close for sampled firms.",
            applicability="Conditional",
            applicability_note="Triggered if BoE samples the entity for cross-border flow / monetary financial institution statistics.",
        ),
        FintechFiling(
            s_no=0,
            category="Statistics",
            area="ONS surveys",
            form_name="Office for National Statistics business surveys (e.g. International Trade in Services)",
            authority="Office for National Statistics",
            frequency="Quarterly / Annual",
            due_date_rule="Within deadline printed on each survey notification (typically 30 days).",
            applicability="Conditional",
        ),
        FintechFiling(
            s_no=0,
            category="Statistics",
            area="Intrastat",
            form_name="Intrastat — movements of goods between NI and EU (and historic GB movements)",
            authority="HMRC",
            frequency="Monthly",
            due_date_rule="By 21st of the following month for in-scope movements above thresholds.",
            applicability="Conditional",
            applicability_note="Post-Brexit only applies to Northern Ireland ↔ EU goods movements above thresholds (£500k arrivals / £250k dispatches). Rarely applicable to a remittance fintech; included for completeness.",
        ),
        FintechFiling(
            s_no=0,
            category="Regulatory",
            area="Annual Financial Crime Report",
            form_name="FIN073 / REP-CRIM — Annual Financial Crime Report",
            authority="FCA",
            frequency="Annual",
            due_date_rule="Within 60 business days of firm's accounting reference date (ARD).",
            payment_due="No filing fee; £250+ administrative penalty for late return + interest.",
            applicability="Conditional",
            applicability_note="Applies to firms with revenue ≥ £5m in the financial-crime regulated business and EMI/PI/AIFM in-scope of REP-CRIM.",
        ),
        FintechFiling(
            s_no=0,
            category="Regulatory",
            area="FCA fees data",
            form_name="FSA056 — Annual periodic-fees tariff data return",
            authority="FCA",
            frequency="Annual",
            due_date_rule="Tariff-data window opens early in each FCA fee year (typically Apr–Jul) via RegData.",
            payment_due="Drives next-year FCA periodic fee + FOS / FSCS / Money & Pensions Service levies. Late submission = estimated fee + administrative fee.",
            applicability="Mandatory",
            applicability_note="All authorised firms with FCA periodic fees must submit tariff data each year.",
        ),
        # === Aspora tracker additions ===
        FintechFiling(
            s_no=0,
            category="Pensions",
            area="Auto-enrolment",
            form_name="Pension remittance",
            authority="The Pensions Regulator / Pension provider",
            frequency="Monthly",
            due_date_rule="Typically by the 22nd of the month following deduction (scheme rules apply).",
            payment_due="Same date as filing.",
            applicability="Conditional",
            applicability_note="Required once the entity employs UK staff above the auto-enrolment threshold.",
        ),
        FintechFiling(
            s_no=0,
            category="Indirect Tax",
            area="VAT (Making Tax Digital)",
            form_name="MTD VAT return",
            authority="HMRC",
            frequency="Quarterly",
            due_date_rule="One month and 7 days after the VAT period end.",
            payment_due="Same date as filing.",
            applicability="Conditional",
            applicability_note="Mandatory for VAT-registered businesses (turnover > £85k or voluntary registration).",
        ),
        FintechFiling(
            s_no=0,
            category="Direct Tax",
            area="Corporation Tax",
            form_name="CT600 — Corporation Tax Return",
            authority="HMRC",
            frequency="Annual",
            due_date_rule="Within 12 months of the end of the accounting period.",
            payment_due="9 months and 1 day after the end of the accounting period (instalments for large companies).",
            applicability="Mandatory",
        ),
        FintechFiling(
            s_no=0,
            category="Corporate",
            area="Statutory Accounts",
            form_name="Companies House — Statutory Financial Statements",
            authority="Companies House",
            frequency="Annual",
            due_date_rule="9 months after the end of the accounting period (private companies); 6 months (public).",
            applicability="Mandatory",
        ),
        FintechFiling(
            s_no=0,
            category="HR / Payroll",
            area="PAYE / Real-Time Information",
            form_name="PAYE / RTI (FPS / EPS)",
            authority="HMRC",
            frequency="Monthly",
            due_date_rule="FPS on or before each pay date; EPS by the 19th of the following month.",
            payment_due="By the 22nd of the following month (electronic) or 19th (postal).",
            applicability="Conditional",
            applicability_note="Required once the entity runs a PAYE scheme.",
        ),
        FintechFiling(
            s_no=0,
            category="Regulatory",
            area="FCA periodic return",
            form_name="FCA Periodic Regulatory Return (RegData)",
            authority="FCA",
            frequency="Semi-annual / Annual",
            due_date_rule="Per the firm's RegData reporting schedule (varies by permission type).",
            applicability="Conditional",
            applicability_note="Required for any FCA-authorised firm.",
        ),
        FintechFiling(
            s_no=0,
            category="Regulatory",
            area="Fraud reporting",
            form_name="Fraud Reporting (REP017)",
            authority="FCA",
            frequency="Periodic",
            due_date_rule="Per the FCA's REP017 reporting cadence — typically annual with event-based escalation.",
            applicability="Conditional",
            applicability_note="Required for in-scope payment, e-money, and other regulated firms.",
        ),
        FintechFiling(
            s_no=0,
            category="Regulatory",
            area="Complaints reporting",
            form_name="Complaints Reporting (DISP)",
            authority="FCA",
            frequency="Semi-annual / Annual",
            due_date_rule="Within 30 business days of the end of each reporting period set by FCA DISP rules.",
            applicability="Mandatory",
            applicability_note="All FCA-authorised firms — even nil returns must be submitted.",
        ),
        FintechFiling(
            s_no=0,
            category="Regulatory",
            area="Change notifications",
            form_name="Change notifications (Controllers, Directors, Business Model)",
            authority="FCA",
            frequency="Event-based",
            due_date_rule="Notify FCA within the time set by SUP 11 / SUP 15 for the relevant change.",
            applicability="Mandatory",
            applicability_note="Triggered by any qualifying change in control, senior personnel, or business model.",
        ),
        FintechFiling(
            s_no=0,
            category="AML / CFT",
            area="Risk assessment",
            form_name="AML Risk Assessment & Policy Review",
            authority="FCA / HMRC",
            frequency="Annual",
            due_date_rule="Annual refresh; trigger an interim review on any material change in business or customer base.",
            applicability="Mandatory",
        ),
        FintechFiling(
            s_no=0,
            category="Data Protection",
            area="Data protection fee",
            form_name="ICO Registration Renewal",
            authority="ICO",
            frequency="Annual",
            due_date_rule="Before the annual ICO registration anniversary.",
            payment_due="£40 / £60 / £2,900 depending on tier.",
            applicability="Mandatory",
            applicability_note="Required for any UK data controller (with limited exemptions).",
        ),
    ]


FILINGS = _build()
