"""UK filing catalog for a remittance fintech (FCA Authorised Payment Institution)."""
from __future__ import annotations

from compliance_agent.fintech import FintechFiling


def _build() -> list[FintechFiling]:
    return [
        # === Licensing & Authorization ===
        FintechFiling(
            s_no=0,
            category="Licensing & Authorization",
            area="Payment Services",
            form_name="FCA Authorised Payment Institution permission (PSR 2017) + ongoing change-in-control notifications",
            authority="FCA",
            frequency="One-time + Event-based",
            due_date_rule="Authorization before commencement; change-in-control notification before completion of change.",
            payment_due="Application fee ~£5,000 (small PI) to £25,000 (API); annual periodic fee per FCA fee-block A.10 (minimum ~£1,151).",
            applicability="Mandatory",
        ),
        FintechFiling(
            s_no=0,
            category="Licensing & Authorization",
            area="Regulatory reporting",
            form_name="FCA Regulatory Returns (FSA056 / REP017 etc.) via GABRIEL/RegData",
            authority="FCA",
            frequency="Monthly / Quarterly / Annual",
            due_date_rule="Per RegData schedule for each return — typically 15–30 business days after period close.",
            applicability="Mandatory",
        ),
        FintechFiling(
            s_no=0,
            category="Licensing & Authorization",
            area="Safeguarding",
            form_name="Annual safeguarding audit + monthly safeguarding reconciliation",
            authority="FCA",
            frequency="Annual + Monthly",
            due_date_rule="Annual audit within 4 months of FY close; safeguarding reconciliation as often as accounting records are produced.",
            applicability="Mandatory",
        ),
        FintechFiling(
            s_no=0,
            category="Licensing & Authorization",
            area="Senior Managers & Certification Regime",
            form_name="SMCR Form A (approvals), Conduct Rules training, annual certification",
            authority="FCA",
            frequency="Annual + Event-based",
            due_date_rule="Approvals before role start; annual certification at least once every 12 months.",
            applicability="Mandatory",
        ),

        # === AML / CFT ===
        FintechFiling(
            s_no=0,
            category="AML / CFT",
            area="Suspicious Activity Reports",
            form_name="SAR / DAML submissions to NCA via SAR Online",
            authority="National Crime Agency (NCA)",
            frequency="Event-based",
            due_date_rule="As soon as practicable after suspicion forms; DAML (defence) before proceeding with the transaction.",
            applicability="Mandatory",
        ),
        FintechFiling(
            s_no=0,
            category="AML / CFT",
            area="MLR 2017",
            form_name="Annual MLRO report + business-wide risk assessment refresh",
            authority="Internal + FCA on request",
            frequency="Annual",
            due_date_rule="Within 90 days of FY close.",
            applicability="Mandatory",
        ),
        FintechFiling(
            s_no=0,
            category="AML / CFT",
            area="Sanctions",
            form_name="OFSI consolidated sanctions list screening + reports of breaches/frozen funds",
            authority="OFSI (HM Treasury)",
            frequency="Continuous + Event-based + Annual",
            due_date_rule="Screening on every transaction; breach reports as soon as practicable; annual frozen-funds report by deadline OFSI sets each year.",
            applicability="Mandatory",
        ),

        # === Consumer Protection ===
        FintechFiling(
            s_no=0,
            category="Consumer Protection",
            area="Consumer Duty",
            form_name="FCA Consumer Duty — annual board attestation + outcomes monitoring",
            authority="FCA",
            frequency="Annual",
            due_date_rule="Annual board review and attestation within 12 months of last (first by 31 Jul 2024).",
            applicability="Mandatory",
        ),
        FintechFiling(
            s_no=0,
            category="Consumer Protection",
            area="Complaints",
            form_name="DISP complaints return + Financial Ombudsman cooperation",
            authority="FCA / Financial Ombudsman Service",
            frequency="Half-Yearly",
            due_date_rule="30 business days after each reporting period (DISP 1 Annex 1).",
            applicability="Mandatory",
        ),
        FintechFiling(
            s_no=0,
            category="Consumer Protection",
            area="APP fraud reimbursement",
            form_name="PSR Authorised Push Payment Fraud reimbursement — data reporting",
            authority="PSR / Pay.UK",
            frequency="Monthly / Quarterly",
            due_date_rule="Per PSR mandatory reimbursement scheme (effective Oct 2024) — data submissions on the PSR schedule.",
            applicability="Conditional",
            applicability_note="Applies to Faster Payments and CHAPS participants serving consumers in the UK.",
        ),

        # === Data Protection ===
        FintechFiling(
            s_no=0,
            category="Data Protection & Privacy",
            area="UK GDPR / DPA 2018",
            form_name="UK GDPR + DPA 2018 — ICO registration, DPO contact, ROPA, 72h breach reports",
            authority="Information Commissioner's Office (ICO)",
            frequency="Annual + Continuous + Event-based",
            due_date_rule="ICO data-protection fee paid annually on anniversary; breach to ICO within 72 hours of awareness.",
            payment_due="ICO fee — Tier 1 £40 (turnover ≤£632k or ≤10 staff), Tier 2 £60 (≤£36m or ≤250 staff), Tier 3 £2,900 (larger).",
            applicability="Mandatory",
        ),

        # === Cybersecurity ===
        FintechFiling(
            s_no=0,
            category="Cybersecurity",
            area="Operational resilience",
            form_name="FCA / Bank of England Operational Resilience policy — important business services & impact tolerances",
            authority="FCA",
            frequency="Continuous + Annual review",
            due_date_rule="Self-assessment maintained; full operational-resilience compliance by 31 Mar 2025.",
            applicability="Mandatory",
        ),
        FintechFiling(
            s_no=0,
            category="Cybersecurity",
            area="Incident reporting",
            form_name="FCA Principle 11 incident notifications + REP018 operational/security incident reporting",
            authority="FCA",
            frequency="Event-based",
            due_date_rule="As soon as reasonably practicable on becoming aware of a material incident.",
            applicability="Mandatory",
        ),

        # === Tax ===
        FintechFiling(
            s_no=0,
            category="Direct Tax",
            area="Corporation Tax",
            form_name="CT600 + iXBRL accounts + Corporation Tax payment",
            authority="HMRC",
            frequency="Annual + Quarterly (large)",
            due_date_rule="CT600 within 12 months of FY close; CT payment within 9 months & 1 day (large companies on quarterly instalments).",
            payment_due="UK Corporation Tax = 25% on profits > £250k (19% main rate up to £50k, marginal relief between). Late-payment interest rate per HMRC (currently 8.0%).",
            applicability="Mandatory",
        ),
        FintechFiling(
            s_no=0,
            category="Indirect Tax (VAT)",
            area="VAT",
            form_name="VAT return (Making Tax Digital)",
            authority="HMRC",
            frequency="Quarterly",
            due_date_rule="Filing + payment within 1 month and 7 days after VAT-quarter close.",
            payment_due="VAT = output VAT less input VAT. Default surcharge regime — 2%, 5%, 10%, 15% of unpaid VAT for repeated lateness.",
            applicability="Mandatory",
        ),
        FintechFiling(
            s_no=0,
            category="Labor & Payroll",
            area="PAYE",
            form_name="PAYE / NIC RTI submissions (FPS / EPS) + P11D",
            authority="HMRC",
            frequency="Monthly + Annual",
            due_date_rule="FPS on or before each payday; P11D for benefits by 6 Jul; PAYE settlement payments per HMRC schedule.",
            payment_due="By the 22nd of the following month (electronic).",
            applicability="Mandatory",
        ),

        # === Corporate ===
        FintechFiling(
            s_no=0,
            category="Corporate & Statutory",
            area="Companies House",
            form_name="Confirmation Statement (CS01) + Annual Accounts + PSC register updates",
            authority="Companies House",
            frequency="Annual + Event-based",
            due_date_rule="Confirmation Statement within 14 days of review date; accounts within 9 months of FY close; PSC updates within 14 days of internal record and 14 days more to register.",
            payment_due="CS01 fee £34 online (£62 paper). Late accounts penalty £150–£1,500 (private), doubled if late in two consecutive years.",
            applicability="Mandatory",
        ),
        FintechFiling(
            s_no=0,
            category="Corporate & Statutory",
            area="ECCT 2023",
            form_name="Economic Crime and Corporate Transparency Act — identity verification, ACSP registration",
            authority="Companies House",
            frequency="Continuous + Event-based",
            due_date_rule="Per Companies House phased implementation through 2024–2026.",
            applicability="Mandatory",
        ),

        # === Additional UK entries ===
        FintechFiling(
            s_no=0,
            category="Labor & Payroll",
            area="Auto-enrolment pensions",
            form_name="Auto-enrolment pension contributions (monthly remittance)",
            authority="The Pensions Regulator / scheme provider",
            frequency="Monthly",
            due_date_rule="Typically by 22nd of the month following deduction (scheme rules apply).",
            payment_due="Employer minimum 3% + employee 5% of qualifying earnings (total 8%). Scheme-specific late-payment notices to TPR.",
            applicability="Mandatory",
            applicability_note="Mandatory once any UK employee aged 22–SPA earning ≥£10,000 is present.",
        ),
        FintechFiling(
            s_no=0,
            category="Labor & Payroll",
            area="Pensions re-enrolment",
            form_name="Re-enrolment + Declaration of Compliance to TPR",
            authority="The Pensions Regulator",
            frequency="Every 3 years",
            due_date_rule="Re-enrol eligible jobholders every 3 years from staging date; declaration within 5 months of re-enrolment date.",
            payment_due="No filing fee; £400 fixed penalty + escalating daily penalty (£50–£10,000) on default.",
            applicability="Mandatory",
        ),
        FintechFiling(
            s_no=0,
            category="Labor & Payroll",
            area="P11D(b) Class 1A NIC",
            form_name="P11D(b) — Class 1A NIC return on benefits in kind",
            authority="HMRC",
            frequency="Annual",
            due_date_rule="By 6 Jul following tax year-end (5 Apr).",
            payment_due="Class 1A NIC @ 13.8% on taxable benefits; payable by 22 Jul (electronic).",
            applicability="Conditional",
            applicability_note="Required if any P11D-reportable benefits provided to employees.",
        ),
        FintechFiling(
            s_no=0,
            category="Labor & Payroll",
            area="Employment-Related Securities",
            form_name="ERS annual return (incl. EMI / CSOP / unapproved schemes)",
            authority="HMRC",
            frequency="Annual",
            due_date_rule="By 6 Jul following tax year-end.",
            payment_due="No payment, but £100 late penalty + further £300 escalations.",
            applicability="Conditional",
            applicability_note="Required if any employee share-incentive scheme exists (incl. growth shares, EMI options).",
        ),
        FintechFiling(
            s_no=0,
            category="Direct Tax",
            area="Corporation Tax QIP",
            form_name="Corporation Tax — Quarterly Instalment Payments (large/very large companies)",
            authority="HMRC",
            frequency="Quarterly",
            due_date_rule="Large (profits > £1.5m): 4 instalments — 7th month of AP, 10th month of AP, 13th, 16th. Very large (> £20m): brought forward by 4 months.",
            payment_due="25% of expected total CT per instalment. Interest 4–8% on underpaid instalments (HMRC late-interest rate).",
            applicability="Conditional",
            applicability_note="Mandatory once augmented profits cross £1.5m threshold (group-adjusted).",
        ),
        FintechFiling(
            s_no=0,
            category="Direct Tax",
            area="Senior Accounting Officer",
            form_name="SAO certificate (Senior Accounting Officer)",
            authority="HMRC",
            frequency="Annual",
            due_date_rule="With annual accounts (within 9 months of FY close).",
            payment_due="No filing fee; £5,000 personal penalty on SAO for failure to certify or notify; further £5,000 on the company.",
            applicability="Conditional",
            applicability_note="Required if UK turnover > £200m or balance sheet > £2bn (group level).",
        ),
        FintechFiling(
            s_no=0,
            category="Consumer Protection",
            area="Modern Slavery",
            form_name="Modern Slavery Statement (s.54 Modern Slavery Act 2015)",
            authority="Home Office (online register)",
            frequency="Annual",
            due_date_rule="Within 6 months of FY close; published on the company website and Home Office register.",
            applicability="Conditional",
            applicability_note="Required if global turnover ≥ £36m and any UK business presence.",
        ),
        FintechFiling(
            s_no=0,
            category="Labor & Payroll",
            area="Gender Pay Gap",
            form_name="Gender Pay Gap Report",
            authority="Government Equalities Office / GOV.UK portal",
            frequency="Annual",
            due_date_rule="By 4 Apr each year (private sector) for snapshot 5 Apr prior.",
            applicability="Conditional",
            applicability_note="Required if ≥ 250 UK employees on snapshot date.",
        ),
        FintechFiling(
            s_no=0,
            category="Data Protection & Privacy",
            area="CRS / FATCA",
            form_name="HMRC FATCA / CRS reporting (Form CRS / FATCA XML schema)",
            authority="HMRC",
            frequency="Annual",
            due_date_rule="By 31 May following calendar year.",
            payment_due="No fee; £300 penalty per return + £60/day for continued failure.",
            applicability="Conditional",
            applicability_note="Required if classified as a Financial Institution under CRS; many e-money/PI firms qualify.",
        ),
        FintechFiling(
            s_no=0,
            category="AML / CFT",
            area="HMRC AML supervision",
            form_name="HMRC AML supervised business — annual fees + register update (if not FCA-supervised)",
            authority="HMRC",
            frequency="Annual",
            due_date_rule="Per HMRC anniversary cycle; nomination fees due on registration.",
            payment_due="Registration fee £300 per premises; renewal fee £300/yr; approval test fee £150 per nominated officer.",
            applicability="Conditional",
            applicability_note="HMRC-supervised only — FCA-authorised PIs are FCA-supervised for AML and skip this.",
        ),
        FintechFiling(
            s_no=0,
            category="Consumer Protection",
            area="FSCS",
            form_name="Financial Services Compensation Scheme tariff data submission",
            authority="FSCS via FCA",
            frequency="Annual",
            due_date_rule="Tariff data window typically Jul–Sep each year via FCA RegData.",
            payment_due="FSCS levy per class — variable; small PIs typically exempt from class-specific levies.",
            applicability="Conditional",
        ),
        FintechFiling(
            s_no=0,
            category="Direct Tax",
            area="Off-payroll working",
            form_name="IR35 / Off-Payroll Working (ITEPA Ch.10) compliance",
            authority="HMRC",
            frequency="Continuous",
            due_date_rule="Status Determination Statement issued before any engagement begins; client-led status decisions for medium/large businesses.",
            applicability="Conditional",
            applicability_note="Required if engaging contractors via intermediary entities (PSCs) and company is medium/large.",
        ),
    ]


FILINGS = _build()
